#include "digitor/timeline.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace digitor {
void Timeline::checkpoint(){undo_.push_back({tracks_});redo_.clear();}
std::size_t Timeline::add_track(std::string n){checkpoint();tracks_.push_back({std::move(n),{}});return tracks_.size()-1;}
void Timeline::sort(std::size_t t){std::sort(tracks_[t].clips.begin(),tracks_[t].clips.end(),[](auto&a,auto&b){return a.start<b.start;});}
Clip* Timeline::find_mut(ClipId id){for(auto&t:tracks_)for(auto&c:t.clips)if(c.id==id)return &c;return nullptr;} const Clip*Timeline::find(ClipId id)const{for(auto&t:tracks_)for(auto&c:t.clips)if(c.id==id)return &c;return nullptr;}
void Timeline::resolve_overwrite(std::size_t t,ClipId id,FrameNumber a,FrameNumber b){auto&v=tracks_[t].clips;std::vector<Clip> result;for(auto c:v){if(c.id==id||c.end()<=a||c.start>=b){result.push_back(std::move(c));continue;}auto original_end=c.end();if(c.start<a){auto left=c;left.duration=a-left.start;result.push_back(std::move(left));}if(original_end>b){c.id=next_id_++;c.source_in+=b-c.start;c.start=b;c.duration=original_end-b;result.push_back(std::move(c));}}v=std::move(result);}
ClipId Timeline::add_clip(std::size_t t,const std::string&s,FrameNumber start,FrameNumber duration,FrameNumber in,EditMode mode){if(t>=tracks_.size()||start<0||duration<=0||in<0)throw std::invalid_argument("invalid clip");checkpoint();Clip c{next_id_++,s,start,duration,in,{}};if(mode==EditMode::insert){std::vector<Clip> tails;for(auto&x:tracks_[t].clips){if(x.start>=start)x.start+=duration;else if(x.end()>start){auto tail=x;tail.id=next_id_++;tail.source_in+=start-x.start;tail.start=start+duration;tail.duration=x.end()-start;x.duration=start-x.start;tails.push_back(std::move(tail));}}tracks_[t].clips.insert(tracks_[t].clips.end(),tails.begin(),tails.end());}else{resolve_overwrite(t,c.id,start,start+duration);}tracks_[t].clips.push_back(c);sort(t);return c.id;}
bool Timeline::erase(ClipId id,bool rip){for(auto&t:tracks_)for(auto i=t.clips.begin();i!=t.clips.end();++i)if(i->id==id){checkpoint();auto end=i->end(),d=i->duration;t.clips.erase(i);if(rip)for(auto&c:t.clips)if(c.start>=end)c.start-=d;return true;}return false;}
bool Timeline::move(ClipId id,std::size_t target,FrameNumber start,EditMode mode){if(target>=tracks_.size()||start<0)return false;auto*c=find_mut(id);if(!c)return false;checkpoint();Clip copy=*c;for(auto&t:tracks_)t.clips.erase(std::remove_if(t.clips.begin(),t.clips.end(),[&](auto&x){return x.id==id;}),t.clips.end());copy.start=start;if(mode==EditMode::insert){for(auto&x:tracks_[target].clips)if(x.start>=start)x.start+=copy.duration;}else{resolve_overwrite(target,id,start,start+copy.duration);}tracks_[target].clips.push_back(copy);sort(target);return true;}
bool Timeline::ripple(ClipId id,FrameNumber delta){auto*c=find_mut(id);if(!c||c->duration+delta<=0)return false;checkpoint();auto old=c->end();c->duration+=delta;for(auto&t:tracks_)for(auto&x:t.clips)if(x.id!=id&&x.start>=old)x.start+=delta;return true;}
bool Timeline::roll(ClipId l,ClipId r,FrameNumber d){auto*a=find_mut(l),*b=find_mut(r);if(!a||!b||a->end()!=b->start||a->duration+d<=0||b->duration-d<=0)return false;checkpoint();a=find_mut(l);b=find_mut(r);a->duration+=d;b->start+=d;b->source_in+=d;b->duration-=d;return true;}
bool Timeline::slip(ClipId id,FrameNumber d){auto*c=find_mut(id);if(!c||c->source_in+d<0)return false;checkpoint();find_mut(id)->source_in+=d;return true;}
bool Timeline::slide(ClipId id,FrameNumber d){auto*c=find_mut(id);if(!c||c->start+d<0)return false;checkpoint();find_mut(id)->start+=d;for(std::size_t i=0;i<tracks_.size();++i)sort(i);return true;}
bool Timeline::set_keyframe(ClipId id,FrameNumber f,double v){auto*c=find_mut(id);if(!c||f<0||f>c->duration)return false;checkpoint();c=find_mut(id);auto i=std::lower_bound(c->keyframes.begin(),c->keyframes.end(),f,[](auto&k,auto x){return k.frame<x;});if(i!=c->keyframes.end()&&i->frame==f)i->value=v;else c->keyframes.insert(i,{f,v});return true;}
std::optional<double> Timeline::value_at(ClipId id,FrameNumber f)const{auto*c=find(id);if(!c||c->keyframes.empty())return{};auto i=std::lower_bound(c->keyframes.begin(),c->keyframes.end(),f,[](auto&k,auto x){return k.frame<x;});if(i==c->keyframes.begin())return i->value;if(i==c->keyframes.end())return c->keyframes.back().value;if(i->frame==f)return i->value;auto&a=*(i-1);double x=double(f-a.frame)/double(i->frame-a.frame);return a.value+(i->value-a.value)*x;}
bool Timeline::undo(){if(undo_.empty())return false;redo_.push_back({tracks_});tracks_=std::move(undo_.back().tracks);undo_.pop_back();return true;}bool Timeline::redo(){if(redo_.empty())return false;undo_.push_back({tracks_});tracks_=std::move(redo_.back().tracks);redo_.pop_back();return true;}
std::vector<Gap> Timeline::gaps(std::size_t track,FrameNumber through)const{if(track>=tracks_.size()||through<0)throw std::invalid_argument("invalid gap range");std::vector<Gap> result;FrameNumber cursor{};for(const auto&clip:tracks_[track].clips){if(clip.start>cursor)result.push_back({cursor,clip.start-cursor});cursor=std::max(cursor,clip.end());}if(cursor<through)result.push_back({cursor,through-cursor});return result;}
std::vector<ScheduledClip> Timeline::schedule(FrameNumber frame)const{if(frame<0)throw std::invalid_argument("negative frame");std::vector<ScheduledClip> result;for(std::size_t track=0;track<tracks_.size();++track)for(const auto&clip:tracks_[track].clips)if(frame>=clip.start&&frame<clip.end()){auto local=clip.source_in+frame-clip.start;if(auto nested_timeline=nested(clip.id)){auto children=nested_timeline->schedule(local);for(auto child:children){child.timeline_frame=frame;result.push_back(child);}}else result.push_back({track,clip.id,frame,local});}return result;}
ClipId Timeline::add_nested(std::size_t track,const Timeline&timeline,FrameNumber start,EditMode mode){if(timeline.frame_rate().numerator!=rate_.numerator||timeline.frame_rate().denominator!=rate_.denominator)throw std::invalid_argument("nested timeline frame rate mismatch");FrameNumber duration{};for(const auto&t:timeline.tracks())for(const auto&clip:t.clips)duration=std::max(duration,clip.end());if(duration<=0)throw std::invalid_argument("nested timeline is empty");auto id=add_clip(track,"nested://"+std::to_string(next_id_),start,duration,0,mode);nested_[id]=std::make_shared<Timeline>(timeline);return id;}
const Timeline* Timeline::nested(ClipId id)const{auto found=nested_.find(id);return found==nested_.end()?nullptr:found->second.get();}
}
