cmake_minimum_required(VERSION 3.21)
project(DigitorConsumer LANGUAGES C CXX)
find_package(DigitorEngine CONFIG REQUIRED)
add_executable(c_consumer main.c)
set_target_properties(c_consumer PROPERTIES C_STANDARD 11)
target_link_libraries(c_consumer PRIVATE Digitor::digitor_engine)
add_executable(cxx_consumer main.cpp)
target_link_libraries(cxx_consumer PRIVATE Digitor::digitor_engine)
enable_testing()
add_test(NAME installed_c_consumer COMMAND c_consumer)
add_test(NAME installed_cxx_consumer COMMAND cxx_consumer)
