#include "digitor/primary_wheels.hpp"
#include "digitor/rgb_curves.hpp"
#include "gpu/gpu_backend.hpp"
#include "gpu/native_primary_wheels.hpp"
#include <cassert>
#include <cmath>
#include <limits>
#include <vector>
namespace { class WheelsBackend final:public digitor::IRenderBackend{public:bool initialize(bool)override{return true;}void shutdown()noexcept override{}DigitorRendererInfo info()const noexcept override{return {};}protected:DigitorResult execute_process_primary_wheels_gpu(std::span<const digitor::Color>,uint32_t w,uint32_t h,int64_t ts,const digitor::PrimaryWheelsParameters&p,digitor::ProcessedGpuFramePtr&out)noexcept override{begin_grade_provenance(DIGITOR_RENDERER_VULKAN,true,"test-adapter","test","wheels","pipeline");provenance_.primary_wheels_enabled=true;provenance_.primary_wheels_parameter_identity=p.identity();provenance_.primary_wheels_source_bound=provenance_.primary_wheels_destination_bound=provenance_.primary_wheels_parameters_bound=provenance_.output_written=true;out=std::make_shared<digitor::ProcessedGpuFrame>(this,DIGITOR_RENDERER_VULKAN,digitor::GpuFrameMetadata{w,h,DIGITOR_PIXEL_FORMAT_RGBA32_FLOAT,digitor::GpuFrameAlpha::straight,ts,"linear-rgba"},99,std::make_shared<int>(1),std::make_shared<std::atomic_bool>(true),true);return DIGITOR_RESULT_OK;}}; }
namespace {class ChainBackend final:public digitor::IRenderBackend{std::uint64_t id_{200};digitor::ProcessedGpuFramePtr make(std::uint32_t w,std::uint32_t h,std::int64_t ts){return std::make_shared<digitor::ProcessedGpuFrame>(this,DIGITOR_RENDERER_VULKAN,digitor::GpuFrameMetadata{w,h,DIGITOR_PIXEL_FORMAT_RGBA32_FLOAT,digitor::GpuFrameAlpha::straight,ts,"fixture-linear"},id_++,std::make_shared<int>(1),std::make_shared<std::atomic_bool>(true),true);}public:int uploads{},intermediates{};bool initialize(bool)override{return true;}void shutdown()noexcept override{}DigitorRendererInfo info()const noexcept override{DigitorRendererInfo i{};i.backend=DIGITOR_RENDERER_VULKAN;return i;}protected:DigitorResult execute_process_primary_wheels_gpu(std::span<const digitor::Color>,uint32_t w,uint32_t h,int64_t ts,const digitor::PrimaryWheelsParameters&,digitor::ProcessedGpuFramePtr&o)noexcept override{++uploads;o=make(w,h,ts);return DIGITOR_RESULT_OK;}DigitorResult execute_process_curves_gpu(std::span<const digitor::Color>,uint32_t w,uint32_t h,int64_t ts,const digitor::CompiledRgbCurves&,digitor::ProcessedGpuFramePtr&o)noexcept override{++uploads;o=make(w,h,ts);return DIGITOR_RESULT_OK;}DigitorResult execute_process_primary_wheels_gpu(const digitor::GpuSourceResource&s,int64_t ts,const digitor::PrimaryWheelsParameters&,digitor::ProcessedGpuFramePtr&o)noexcept override{++intermediates;o=make(s.width,s.height,ts);return DIGITOR_RESULT_OK;}DigitorResult execute_process_curves_gpu(const digitor::GpuSourceResource&s,int64_t ts,const digitor::CompiledRgbCurves&,digitor::ProcessedGpuFramePtr&o)noexcept override{++intermediates;o=make(s.width,s.height,ts);return DIGITOR_RESULT_OK;}};}
void test_primary_wheels(){using namespace digitor;
 reset_primary_wheels_reference_count();
 auto identity=PrimaryWheelsParameters::create();assert(identity->is_identity()&&identity->serialize()==identity->identity());
 PrimaryWheelsDescriptor legacy_ffi_identity;legacy_ffi_identity.gamma={0,0,0};legacy_ffi_identity.gamma_master=0;legacy_ffi_identity.gain={0,0,0};legacy_ffi_identity.gain_master=0;auto legacy=PrimaryWheelsParameters::create(legacy_ffi_identity);assert(legacy->is_identity());assert(legacy->values().gamma.r==1&&legacy->values().gamma.g==1&&legacy->values().gamma.b==1&&legacy->values().gamma_master==1);assert(legacy->values().gain.r==1&&legacy->values().gain.g==1&&legacy->values().gain.b==1&&legacy->values().gain_master==1);
 Color a{-.25f,1.5f,.5f,.37f};auto b=apply_primary_wheels_reference(a,*identity);assert(b.r==a.r&&b.g==a.g&&b.b==a.b&&b.a==a.a);
 assert(primary_wheels_reference_count()==1);
 PrimaryWheelsDescriptor d;d.lift={.1f,0,0};d.gamma={2,1,1};d.gain={1,2,1};d.offset={0,0,.25f};auto p=PrimaryWheelsParameters::create(d);b=apply_primary_wheels_reference(a,*p);
 auto native_parameters=native_primary_wheels_parameters(*p,15,3,5);assert(native_parameters.lift[0]==.1f&&native_parameters.gamma[0]==2&&native_parameters.gain[1]==2&&native_parameters.offset[2]==.25f&&native_parameters.enabled[0]==1&&native_parameters.pixel_count==15&&native_parameters.width==3&&native_parameters.height==5);
 assert(std::abs(b.r+std::sqrt(.15f))<1e-6f&&b.g==3&&b.b==.75f&&b.a==a.a);
 d.lift_enabled=false;d.gamma_enabled=false;d.gain_enabled=false;d.offset_enabled=false;assert(PrimaryWheelsParameters::create(d)->is_identity());
 d= {};d.lift_master=.1f;d.gamma_master=2;d.gain_master=2;d.offset_master=-.1f;p=PrimaryWheelsParameters::create(d);b=apply_primary_wheels_reference({.15f,.15f,.15f,.2f},*p);assert(b.r==b.g&&b.g==b.b&&b.a==.2f);
 const float inf=std::numeric_limits<float>::infinity(),nan=std::numeric_limits<float>::quiet_NaN();b=apply_primary_wheels_reference({inf,nan,-2,.4f},*p);assert(b.r==inf&&std::isnan(b.g)&&std::isfinite(b.b)&&b.a==.4f);
 bool bad=false;try{d.gain.r=nan;(void)PrimaryWheelsParameters::create(d);}catch(const std::invalid_argument&){bad=true;}assert(bad);
 std::vector<Color> in(15,a),out(15);apply_primary_wheels_reference(in,out,*identity);for(auto v:out)assert(v.r==a.r&&v.g==a.g&&v.b==a.b&&v.a==a.a);
 RenderGraph graph;auto s=graph.import_resource({.size=in.size()*sizeof(Color),.transient=false,.initial_state=ResourceState::shader_read,.name="input"}),o=graph.create_transient(out.size()*sizeof(Color));add_primary_wheels_cpu_pass(graph,s,o,identity,in,out);graph.compile();CommandQueue q;graph.execute(q);assert(graph.order().size()==1);
 // User-defined graph ordering is supported and remains explicit: exercise
 // both Primary Wheels -> RGB Curves and the reverse comparison ordering.
 for(bool wheels_first:{false,true}){RenderGraph chain;auto input=chain.import_resource({.size=64,.transient=false,.initial_state=ResourceState::shader_read,.name="chain-input"});auto middle=chain.create_transient(64),output=chain.create_transient(64);int sequence=0;
   auto wheels=[&](CommandEncoder&e){e.dispatch([&]{sequence=sequence*10+1;});};auto curves=[&](CommandEncoder&e){e.dispatch([&]{sequence=sequence*10+2;});};
   if(wheels_first){add_primary_wheels_pass(chain,input,middle,wheels);add_rgb_curves_pass(chain,middle,output,curves);}else{add_rgb_curves_pass(chain,input,middle,curves);add_primary_wheels_pass(chain,middle,output,wheels);}chain.export_resource(output);chain.compile();CommandQueue cq;chain.execute(cq);assert(sequence==(wheels_first?12:21));assert(chain.schedule()[1].dependencies.size()==1);
 }
 WheelsBackend native;ProcessedGpuFramePtr frame;const auto before=primary_wheels_reference_count();assert(native.process_primary_wheels_gpu(in,3,5,91,*identity,frame)==DIGITOR_RESULT_OK);assert(frame&&frame->identity()==99&&frame->metadata().timestamp==91);const auto&prov=native.execution_provenance();assert(primary_wheels_reference_count()==before&&prov.cpu_primary_wheels_invocations==0&&prov.primary_wheels_fallback_invocations==0&&prov.normal_preview_readback_count==0);
 ProcessedGpuFramePtr retired;
 const void* retired_context=nullptr;
 {auto backend=std::make_unique<WheelsBackend>();retired_context=backend.get();assert(backend->process_primary_wheels_gpu(in,3,5,92,*identity,retired)==DIGITOR_RESULT_OK);assert(retired->context_live()&&retired->ready());}
 assert(!retired->context_live()&&!retired->ready());
 assert(retired->acquire(retired_context,DIGITOR_RENDERER_VULKAN)==DIGITOR_RESULT_NOT_INITIALIZED);
 auto curves=CompiledRgbCurves::compile(RgbCurvesParameters{});ChainBackend chained;
 ProcessedGpuFramePtr first,second;assert(chained.process_primary_wheels_gpu(in,3,5,93,*identity,first)==DIGITOR_RESULT_OK);auto first_source=chained.gpu_source(first);assert(first_source.origin==GpuSourceOrigin::ProcessedFrame&&first_source.color_metadata_identity=="fixture-linear"&&first_source.usable_by(DIGITOR_RENDERER_VULKAN,first_source.context_identity));assert(chained.process_curves_gpu(first_source,94,*curves,second)==DIGITOR_RESULT_OK);
 assert(chained.process_curves_gpu(in,3,5,95,*curves,first)==DIGITOR_RESULT_OK);assert(chained.process_primary_wheels_gpu(chained.gpu_source(first),96,*identity,second)==DIGITOR_RESULT_OK);assert(chained.uploads==2&&chained.intermediates==2);
 auto invalid=chained.gpu_source(first);invalid.backend=DIGITOR_RENDERER_D3D12;assert(chained.process_primary_wheels_gpu(invalid,97,*identity,second)==DIGITOR_RESULT_INVALID_ARGUMENT);invalid=chained.gpu_source(first);++invalid.context_identity;assert(chained.process_primary_wheels_gpu(invalid,97,*identity,second)==DIGITOR_RESULT_INVALID_ARGUMENT);invalid=chained.gpu_source(first);++invalid.width;assert(chained.process_primary_wheels_gpu(invalid,97,*identity,second)==DIGITOR_RESULT_INVALID_ARGUMENT);invalid=chained.gpu_source(first);invalid.format=DIGITOR_PIXEL_FORMAT_RGBA16_FLOAT;assert(chained.process_primary_wheels_gpu(invalid,97,*identity,second)==DIGITOR_RESULT_INVALID_ARGUMENT);invalid=chained.gpu_source(first);invalid.precision=GpuPrecisionMode::Float16;assert(chained.process_primary_wheels_gpu(invalid,97,*identity,second)==DIGITOR_RESULT_INVALID_ARGUMENT);invalid=chained.gpu_source(first);invalid.readiness=GpuReadiness::Pending;assert(chained.process_primary_wheels_gpu(invalid,97,*identity,second)==DIGITOR_RESULT_INVALID_ARGUMENT);assert(chained.uploads==2&&chained.intermediates==2);
}
