#include "digitor/native_node_qualification.hpp"
#include "digitor/native_node_hardware_qualification.hpp"
#include "digitor/native_node_hardware_harness.hpp"
#include "digitor/native_node_production_signoff.hpp"
#include "digitor/native_node_platform_factories.hpp"
#include "digitor/effects.hpp"
#include "digitor/lut.hpp"
#include "digitor/node_graph.hpp"
#include "digitor/production_node_graph.hpp"
#include "digitor/native_node_executor.hpp"
#include "digitor/native_node_kernels.hpp"
#include "digitor/native_node_shader_contracts.hpp"
#include "digitor/native_node_pipeline_runtime.hpp"
#include "digitor/native_node_pipeline_objects.hpp"
#include "digitor/native_node_backend_runtime.hpp"
#include "gpu/gpu_backend.hpp"
#include <cassert>
#include <cmath>
#include <sstream>

namespace {
class NativeGraphFixtureBackend: public digitor::IRenderBackend {
 std::uint64_t next_{9000};
 digitor::ProcessedGpuFramePtr make(std::uint32_t w,std::uint32_t h,std::int64_t ts){return std::make_shared<digitor::ProcessedGpuFrame>(this,DIGITOR_RENDERER_VULKAN,digitor::GpuFrameMetadata{w,h,DIGITOR_PIXEL_FORMAT_RGBA32_FLOAT,digitor::GpuFrameAlpha::straight,ts,"linear-rgba"},next_++,std::make_shared<int>(1),std::make_shared<std::atomic_bool>(true),true);}
public:
 int uploads{},chains{},generic{},mixes{};
 bool supports_native_node_operation(digitor::NodeOperationKind)const noexcept override{return true;} bool supports_native_node_mixer()const noexcept override{return true;}
 bool initialize(bool)override{return true;} void shutdown()noexcept override{} DigitorRendererInfo info()const noexcept override{DigitorRendererInfo i{};i.backend=DIGITOR_RENDERER_VULKAN;return i;}
protected:
 DigitorResult execute_process_primary_wheels_gpu(std::span<const digitor::Color>,std::uint32_t w,std::uint32_t h,std::int64_t ts,const digitor::PrimaryWheelsParameters&,digitor::ProcessedGpuFramePtr&o)noexcept override{++uploads;o=make(w,h,ts);return DIGITOR_RESULT_OK;}
 DigitorResult execute_process_primary_wheels_gpu(const digitor::GpuSourceResource&s,std::int64_t ts,const digitor::PrimaryWheelsParameters&,digitor::ProcessedGpuFramePtr&o)noexcept override{++chains;o=make(s.width,s.height,ts);return DIGITOR_RESULT_OK;}
 DigitorResult execute_process_log_wheels_gpu(const digitor::GpuSourceResource&s,std::int64_t ts,const digitor::LogWheelsParameters&,digitor::ProcessedGpuFramePtr&o)noexcept override{++chains;o=make(s.width,s.height,ts);return DIGITOR_RESULT_OK;}
 DigitorResult execute_process_node_operation_gpu(const digitor::GpuSourceResource&s,std::int64_t ts,const digitor::NodeOperation&,digitor::ProcessedGpuFramePtr&o)noexcept override{++generic;o=make(s.width,s.height,ts);return DIGITOR_RESULT_OK;}
 DigitorResult execute_mix_gpu_sources(std::span<const digitor::GpuSourceResource>s,std::int64_t ts,digitor::ProcessedGpuFramePtr&o)noexcept override{++mixes;o=make(s.front().width,s.front().height,ts);return DIGITOR_RESULT_OK;}
};
}
void test_v2(){using namespace digitor;
 NodeGraph g;int calls=0;auto a=g.add_node("source",[&](const NodeContext&,const std::vector<NodeValue>&){++calls;return NodeValue{{.25f,.5f,.75f,1}};},"source shader");auto b=g.add_node("copy",[](const NodeContext&,const std::vector<NodeValue>&v){return v.at(0);});g.connect(a,b);assert(g.evaluate(b,{7,1,1,{}})[0].g==.5f);g.evaluate(b,{7,1,1,{}});assert(calls==1);std::stringstream serialized;g.serialize(serialized);auto restored=NodeGraph::deserialize(serialized,[](const std::string&){return [](const NodeContext&,const std::vector<NodeValue>&v){return v.empty()?NodeValue{{1,0,0,1}}:v[0];};});assert(restored.size()==2&&restored.evaluate(b,{})[0].r==1);
 g.set_bypassed(b,true);assert(g.evaluate(b,{8,1,1,{}})[0].g==.5f);g.set_bypassed(b,false);NodeValue graph_gpu;CommandBuffer gb;CommandEncoder ge(gb);g.evaluate_gpu(ge,b,{9,1,1,{}},graph_gpu);ge.finish();CommandQueue graph_queue;graph_queue.submit(gb);assert(graph_gpu[0].b==.75f);
 Lut1D one({{0,0,0,1},{1,1,1,1}});Color input{.25f,.5f,.75f,1},cpu{},gpu{};apply_lut_cpu(&input,&cpu,1,one);CommandBuffer cb;CommandEncoder enc(cb);apply_lut_gpu(enc,&input,&gpu,1,one);enc.finish();CommandQueue q;q.submit(cb);assert(std::abs(cpu.b-gpu.b)<1e-7f);
 std::stringstream cube("LUT_3D_SIZE 2\n0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n1 1 1\n");auto three=Lut3D::load_cube(cube);auto c=three.sample(input,LutInterpolation::tetrahedral);assert(std::abs(c.r-input.r)<1e-6f&&std::abs(c.b-input.b)<1e-6f);
 std::stringstream cube1("LUT_1D_SIZE 3\n0 0 0\n.5 .4 .3\n1 1 1\n");auto parsed=parse_cube(cube1);assert(parsed.one_dimensional&&parsed.one_dimensional->values().size()==3);bool malformed=false;try{std::stringstream bad("LUT_3D_SIZE 17\n0 0 0\n");parse_cube(bad);}catch(const std::runtime_error&){malformed=true;}assert(malformed);
 Color image[3]{{1,0,0,1},{0,1,0,1},{0,0,1,1}},effect[3];CommandBuffer eb;CommandEncoder ee(eb);apply_effect_gpu(ee,image,effect,3,1,{EffectType::chromatic_aberration,1,1,0,42});ee.finish();q.submit(eb);assert(effect[1].r==1&&effect[1].g==1&&effect[1].b==1);
 ProductionNodeGraph pg;auto serial=pg.add_serial_after(pg.input_node(),"Grade 1");pg.select_node(serial);PrimaryWheelsDescriptor pd;pd.offset={.1f,0,0};pg.add_operation_to_selected(make_primary_wheels_operation(PrimaryWheelsParameters::create(pd)));pg.add_operation_to_selected(make_power_window_operation({WindowShape::rectangle,.5f,.5f,1,1,0,.1f,1,false}));std::vector<Color> src(4,Color{.2f,.2f,.2f,1});auto graded=pg.render(src,2,2);assert(graded.size()==4&&graded[0].r>.2f);auto branches=pg.add_parallel_after(serial);pg.select_node(branches.first);EffectSettings es;es.type=EffectType::vignette;es.amount=.5f;pg.add_operation_to_selected(make_effect_operation(es));auto parallel=pg.render(src,2,2);assert(parallel.size()==4);pg.remove_node(branches.second);assert(pg.node(branches.first).kind==ProductionNodeKind::serial);assert(!pg.recipe_identity().empty());bool endpoint=false;try{pg.select_node(pg.output_node());}catch(const std::invalid_argument&){endpoint=true;}assert(endpoint);
 pg.set_position(serial,{220,40});assert(pg.node(serial).position.x==220);
 ProductionNodeGraph mirror;auto grade=mirror.add_serial_after(mirror.input_node(),"Grade");mirror.select_node(grade);auto new_branch=mirror.convert_to_parallel(grade,"Parallel 2");assert(mirror.node(grade).kind==ProductionNodeKind::parallel);assert(mirror.node(new_branch).kind==ProductionNodeKind::parallel);mirror.remove_node(new_branch);assert(mirror.node(grade).kind==ProductionNodeKind::serial);auto json=mirror.to_json();assert(json.find("\"nodes\"")!=std::string::npos&&json.find("\"x\"")!=std::string::npos);
 NodeRenderStats cache_first{},cache_second{},cache_changed{};std::vector<Color> cache_src(16,Color{.1f,.2f,.3f,1});auto c1=mirror.render_cached(cache_src,4,4,1,&cache_first);auto c2=mirror.render_cached(cache_src,4,4,1,&cache_second);assert(c1.size()==c2.size()&&std::abs(c1[0].r-c2[0].r)<1e-7f&&cache_first.executed_nodes>0&&cache_second.executed_nodes==0&&cache_second.cache_hits==mirror.execution_order().size());mirror.select_node(grade);PrimaryWheelsDescriptor cache_pd;cache_pd.offset={.01f,0,0};mirror.add_operation_to_selected(make_primary_wheels_operation(PrimaryWheelsParameters::create(cache_pd)));auto c3=mirror.render_cached(cache_src,4,4,1,&cache_changed);assert(c3.size()==c1.size()&&cache_changed.executed_nodes>0&&cache_changed.cache_hits>=1);mirror.clear_render_cache();assert(mirror.cached_node_count()==0);
 ProductionNodeGraph node_stress;NodeId stress_tail=node_stress.input_node();for(int i=0;i<128;++i)stress_tail=node_stress.add_serial_after(stress_tail,"stress");assert(node_stress.execution_order().size()==130);std::vector<Color> stress_pixels(64,Color{.25f,.5f,.75f,1});NodeRenderStats stress_a{},stress_b{};node_stress.render_cached(stress_pixels,8,8,99,&stress_a);node_stress.render_cached(stress_pixels,8,8,99,&stress_b);assert(stress_a.executed_nodes==130&&stress_b.executed_nodes==0&&stress_b.cache_hits==130);
 ProductionNodeGraph budgeted;auto budget_node=budgeted.add_serial_after(budgeted.input_node(),"budgeted");budgeted.set_render_cache_budget_bytes(1024);std::vector<Color> budget_pixels(256,Color{.2f,.3f,.4f,1});NodeRenderStats budget_stats{};budgeted.render_cached(budget_pixels,16,16,1,&budget_stats);assert(budgeted.render_cache_bytes()<=budgeted.render_cache_budget_bytes()||budgeted.cached_node_count()==1);budgeted.render_cached(budget_pixels,16,16,2,&budget_stats);assert(budget_stats.cache_evictions>0||budgeted.cached_node_count()<=1);budgeted.set_render_cache_budget_bytes(0);assert(budgeted.cached_node_count()==0);
 ProductionNodeGraph nested;auto nested_root=nested.add_serial_after(nested.input_node(),"root");auto p1=nested.add_parallel_after(nested_root,"left","right");nested.select_node(p1.first);auto p2=nested.add_parallel_after(p1.first,"nested-left","nested-right");nested.select_node(p2.first);nested.add_operation_to_selected(make_effect_operation(es));auto nested_order=nested.execution_order();assert(nested_order.size()>=8);auto nested_out=nested.render(stress_pixels,8,8);assert(nested_out.size()==stress_pixels.size());nested.remove_node(p2.second);assert(nested.execution_order().size()<nested_order.size());
 class CoreOnlyBackend final: public NativeGraphFixtureBackend { public: bool supports_native_node_operation(NodeOperationKind k)const noexcept override{return k==NodeOperationKind::primary_wheels||k==NodeOperationKind::log_wheels||k==NodeOperationKind::rgb_curves||k==NodeOperationKind::hsl_qualifier;} bool supports_native_node_mixer()const noexcept override{return false;} };
 for(auto backend:{DIGITOR_RENDERER_VULKAN,DIGITOR_RENDERER_D3D12,DIGITOR_RENDERER_METAL,DIGITOR_RENDERER_OPENGL_ES}){auto prepared=prepare_native_node_pipeline(backend,NativeNodeKernel::parallel_mixer,1920,1080);assert(prepared.ready&&prepared.contract_hash!=0&&prepared.geometry.groups_x==240&&prepared.geometry.groups_y==135);auto maskprep=prepare_native_node_pipeline(backend,NativeNodeKernel::masked_composite,1,1);assert(maskprep.ready&&maskprep.geometry.groups_x==1&&maskprep.geometry.groups_y==1);assert(!prepare_native_node_pipeline(backend,NativeNodeKernel::parallel_mixer,0,1080).ready);auto mixc=native_node_pipeline_contract(backend,NativeNodeKernel::parallel_mixer);auto maskc=native_node_pipeline_contract(backend,NativeNodeKernel::masked_composite);assert(validate_native_node_pipeline_contract(mixc));assert(validate_native_node_pipeline_contract(maskc));assert(mixc.local_size_x==8&&mixc.local_size_y==8);assert(maskc.local_size_x==8&&maskc.local_size_y==8);if(backend==DIGITOR_RENDERER_VULKAN){assert(mixc.uses_push_constants);assert(mixc.source.find("#version 450")!=std::string_view::npos);}if(backend==DIGITOR_RENDERER_OPENGL_ES){assert(!mixc.uses_push_constants);assert(mixc.source.find("#version 310 es")!=std::string_view::npos);assert(mixc.source.find("push_constant")==std::string_view::npos);}}
 std::uint64_t native_handle_seed=100;int native_creates=0,native_destroys=0,native_dispatches=0;
 NativeNodePipelineObjectCache object_cache(
   [&](const NativeNodeCompiledPipeline& p,std::uint64_t device,std::uintptr_t& handle,std::string& diagnostic){assert(p.ready&&device==77);++native_creates;handle=++native_handle_seed;diagnostic="fixture native pipeline created";return true;},
   [&](std::uintptr_t handle){assert(handle!=0);++native_destroys;},
   [&](std::uintptr_t handle,const NativeNodeDispatchGeometry& g,std::string& diagnostic){assert(handle!=0&&g.groups_x==240&&g.groups_y==135);++native_dispatches;diagnostic.clear();return true;});
 auto native_object=object_cache.acquire(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,1920,1080,77);assert(native_object&&native_object->state==NativeNodePipelineObjectState::ready&&native_creates==1);
 auto native_object_again=object_cache.acquire(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,1920,1080,77);assert(native_object_again==native_object&&native_creates==1&&object_cache.counters().cache_hits==1);
 std::string dispatch_diagnostic;assert(object_cache.dispatch(native_object,{240,135,1},dispatch_diagnostic)&&native_dispatches==1);
 object_cache.retire_device(77);assert(object_cache.size()==0&&native_destroys==1&&object_cache.counters().retires==1);
 assert(!object_cache.acquire(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,1920,1080,0));
 int compiled_binaries=0,backend_pipelines=0,backend_destroys=0,recorded_dispatches=0;
 NativeNodeBackendRuntime backend_runtime(
   [&](const NativeNodeCompiledPipeline& p,NativeNodeShaderBinary& b,std::string& d){++compiled_binaries;b.contract_hash=p.contract_hash;b.format=p.backend==DIGITOR_RENDERER_VULKAN?NativeNodeBinaryFormat::spirv:NativeNodeBinaryFormat::dxil;b.bytes.assign(16,std::byte{1});d.clear();return true;},
   [&](const NativeNodeCompiledPipeline&,const NativeNodeShaderBinary&,std::uint64_t dev,NativeNodeBackendPipelineHandle& h,std::string& d){assert(dev==88);++backend_pipelines;h.pipeline=700;h.layout=701;d.clear();return true;},
   [&](const NativeNodeBackendPipelineHandle& h){assert(h.pipeline==700);++backend_destroys;},
   [&](const NativeNodeBackendPipelineHandle& h,const NativeNodeDispatchGeometry& g,const NativeNodeDispatchResources&,std::string& d){assert(h.pipeline==700&&g.groups_x==2&&g.groups_y==2);++recorded_dispatches;d.clear();return true;});
 NativeNodeDispatchResources mix_resources;for(std::uint32_t slot=0;slot<3;++slot)mix_resources.textures.push_back({slot,100+slot,16,16});mix_resources.constants.resize(16);
 std::string backend_diag;assert(backend_runtime.dispatch(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,16,16,88,mix_resources,backend_diag));assert(compiled_binaries==1&&backend_pipelines==1&&recorded_dispatches==1);
 assert(backend_runtime.dispatch(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,16,16,88,mix_resources,backend_diag));assert(compiled_binaries==1&&backend_pipelines==1&&recorded_dispatches==2&&backend_runtime.size()==1);
 auto invalid_resources=mix_resources;invalid_resources.textures.pop_back();assert(!backend_runtime.dispatch(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,16,16,88,invalid_resources,backend_diag));
 { NativeNodeDescriptorRetirementQueue retire; retire.retain(11,3); retire.retain(22,7); assert(retire.size()==2); auto first=retire.collect(3); assert(first.size()==1&&first[0]==11&&retire.size()==1); auto second=retire.collect(7); assert(second.size()==1&&second[0]==22&&retire.size()==0); }
 backend_runtime.retire_device(88);assert(backend_runtime.size()==0&&backend_destroys==1);
 NativeGraphFixtureBackend native_backend;ProductionNodeGraph ng;auto nn=ng.add_serial_after(ng.input_node());ng.select_node(nn);ng.add_operation_to_selected(make_primary_wheels_operation(PrimaryWheelsParameters::create(pd)));LogWheelsDescriptor ld;ng.add_operation_to_selected(make_log_wheels_operation(LogWheelsParameters::create(ld)));auto nr=execute_native_node_graph(native_backend,ng,src,2,2,77);assert(nr.status==NativeNodeGraphStatus::ok&&nr.frame&&native_backend.uploads==1&&native_backend.chains==1);
 ng.add_operation_to_selected(make_effect_operation(es));CoreOnlyBackend core_only;auto pf=preflight_native_node_graph(core_only,ng);assert(!pf.supported&&pf.operation==NodeOperationKind::effect);auto with_effect=execute_native_node_graph(native_backend,ng,src,2,2,78);assert(with_effect.status==NativeNodeGraphStatus::ok&&with_effect.frame&&native_backend.generic==1);
 ProductionNodeGraph dag;auto root=dag.add_serial_after(dag.input_node());dag.select_node(root);dag.add_operation_to_selected(make_primary_wheels_operation(PrimaryWheelsParameters::create(pd)));auto pair=dag.add_parallel_after(root);dag.select_node(pair.first);dag.add_operation_to_selected(make_effect_operation(es));dag.select_node(pair.second);dag.add_operation_to_selected(make_power_window_operation({}));auto dag_preflight=preflight_native_node_graph(native_backend,dag);assert(!dag_preflight.supported&&dag_preflight.node==pair.second&&dag_preflight.operation==NodeOperationKind::power_window);auto dag_result=execute_native_node_graph(native_backend,dag,src,2,2,79);assert(dag_result.status==NativeNodeGraphStatus::unsupported_operation&&!dag_result.frame&&dag_result.node==pair.second&&dag_result.operation==NodeOperationKind::power_window&&native_backend.mixes==0);
 ProductionNodeGraph pass_through;auto empty=pass_through.add_serial_after(pass_through.input_node());auto graded_node=pass_through.add_serial_after(empty);pass_through.select_node(graded_node);pass_through.add_operation_to_selected(make_primary_wheels_operation(PrimaryWheelsParameters::create(pd)));auto pass_result=execute_native_node_graph(native_backend,pass_through,src,2,2,80);assert(pass_result.status==NativeNodeGraphStatus::ok&&pass_result.frame&&native_backend.uploads==2);
 { NativeNodeQualificationRegistry q; auto c=native_node_pipeline_contract(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer); NativeNodeQualificationRecord r{DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer,NativeNodeQualificationState::implemented_unqualified,native_node_pipeline_contract_hash(DIGITOR_RENDERER_VULKAN,NativeNodeKernel::parallel_mixer),"built"}; q.record(r); assert(!q.production_ready(r.backend,r.kernel,r.contract_hash)); r.state=NativeNodeQualificationState::qualified; r.evidence="windows-vulkan-hardware-pass"; q.record(r); assert(q.production_ready(r.backend,r.kernel,r.contract_hash)); assert(!q.production_ready(r.backend,r.kernel,r.contract_hash+1)); q.retire_backend(DIGITOR_RENDERER_VULKAN); assert(!q.production_ready(r.backend,r.kernel,r.contract_hash)); }
 { NativeNodeHardwareQualificationEvidence e; e.backend=DIGITOR_RENDERER_VULKAN; e.kernel=NativeNodeKernel::parallel_mixer; e.contract_hash=native_node_pipeline_contract_hash(e.backend,e.kernel); e.device_identity=1234; e.platform="windows"; e.device_name="fixture-gpu"; e.driver_version="1.0"; e.pipeline_created=e.dispatch_recorded=e.gpu_completed=e.cpu_gpu_parity=e.no_cpu_readback=e.pipeline_cache_reused=e.retirement_invalidated=true; e.max_abs_error=1.0/65535.0; e.evidence_id="fixture-evidence"; std::string qdiag; assert(validate_native_node_hardware_evidence(e,1.0/255.0,qdiag)); auto json=native_node_hardware_evidence_json(e); assert(json.find("parallel_mixer")!=std::string::npos&&json.find("fixture-evidence")!=std::string::npos); e.contract_hash++; assert(!validate_native_node_hardware_evidence(e,1.0/255.0,qdiag)); }
 { NativeNodeProductionSignoff signoff; const auto backend=DIGITOR_RENDERER_VULKAN; const std::vector<NodeOperationKind> required={NodeOperationKind::primary_wheels,NodeOperationKind::log_wheels,NodeOperationKind::rgb_curves,NodeOperationKind::hsl_qualifier,NodeOperationKind::lut1d,NodeOperationKind::lut3d,NodeOperationKind::effect,NodeOperationKind::power_window}; for(auto op:required)signoff.mark_implemented(backend,op,1000u+(std::uint64_t)op); auto pre=signoff.report(backend,required,native_node_pipeline_contract_hash(backend,NativeNodeKernel::parallel_mixer),native_node_pipeline_contract_hash(backend,NativeNodeKernel::masked_composite)); assert(!pre.production_ready); for(auto op:required){ NativeNodeOperationEvidence e; e.backend=backend;e.operation=op;e.implementation_hash=1000u+(std::uint64_t)op;e.device_identity=77;e.platform="windows";e.device_name="fixture";e.driver_version="1";e.native_pipeline_created=e.native_dispatch_completed=e.cpu_gpu_parity=e.no_intermediate_readback=e.cache_reused=e.retirement_invalidated=true;e.max_abs_error=0;e.evidence_id=std::string("op-")+native_node_operation_name(op);std::string d;assert(signoff.record_evidence(e,1.0/255.0,d)); } for(auto k:{NativeNodeKernel::parallel_mixer,NativeNodeKernel::masked_composite}){NativeNodeHardwareQualificationEvidence e;e.backend=backend;e.kernel=k;e.contract_hash=native_node_pipeline_contract_hash(backend,k);e.device_identity=77;e.platform="windows";e.device_name="fixture";e.driver_version="1";e.pipeline_created=e.dispatch_recorded=e.gpu_completed=e.cpu_gpu_parity=e.no_cpu_readback=e.pipeline_cache_reused=e.retirement_invalidated=true;e.max_abs_error=0;e.evidence_id=std::string("kernel-")+native_node_kernel_name(k);signoff.record_kernel_evidence(e,1.0/255.0);} auto done=signoff.report(backend,required,native_node_pipeline_contract_hash(backend,NativeNodeKernel::parallel_mixer),native_node_pipeline_contract_hash(backend,NativeNodeKernel::masked_composite));assert(done.production_ready);auto sj=signoff.report_json(done);assert(sj.find("\"production_ready\":true")!=std::string::npos);signoff.retire_backend(backend);assert(!signoff.report(backend,required,native_node_pipeline_contract_hash(backend,NativeNodeKernel::parallel_mixer),native_node_pipeline_contract_hash(backend,NativeNodeKernel::masked_composite)).production_ready); }

}
