#include "digitor/plugin_app_integration_c.h"
#include <stdio.h>
#include <string.h>

typedef struct State { unsigned installs,updates,uninstalls,recoveries,processes; } State;
static const char* SHA="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
static DigitorResult catalog_count(void* u,size_t* n){(void)u;*n=3;return DIGITOR_RESULT_OK;}
static DigitorResult catalog_read(void* u,size_t i,const char* locale,DigitorPluginAppCatalogItemC* x){(void)u;(void)locale;if(i>=3)return DIGITOR_RESULT_NOT_FOUND;x->plugin_id=i==0?"filter.free":i==1?"effect.paid":"transition.paid";x->version="1.0.0";x->package_sha256=SHA;x->kind=(DigitorPluginAppKindC)i;x->localized_name="Plugin";x->localized_description="Description";x->category="video";x->thumbnail_url="https://example/thumb";x->preview_media_url="https://example/preview";x->minimum_engine_version="4.9.0";return DIGITOR_RESULT_OK;}
static DigitorResult compatible(void* u,const DigitorPluginAppCatalogItemC* x,DigitorPluginAppCompatibilityC* s,char*d,size_t c){(void)u;(void)x;if(c)d[0]=0;*s=DIGITOR_PLUGIN_APP_COMPATIBLE;return DIGITOR_RESULT_OK;}
static DigitorResult install(void* u,const char*i,const char*v,char*d,size_t c){(void)i;(void)v;if(c)d[0]=0;((State*)u)->installs++;return DIGITOR_RESULT_OK;}
static DigitorResult update(void* u,const char*i,const char*v,char*d,size_t c){(void)i;(void)v;if(c)d[0]=0;((State*)u)->updates++;return DIGITOR_RESULT_OK;}
static DigitorResult uninstall(void* u,const char*i,const char*v,char*d,size_t c){(void)i;(void)v;if(c)d[0]=0;((State*)u)->uninstalls++;return DIGITOR_RESULT_OK;}
static DigitorResult installed_count(void* u,size_t*n){(void)u;*n=1;return DIGITOR_RESULT_OK;}
static DigitorResult installed_read(void* u,size_t i,DigitorPluginAppInstalledItemC*x){(void)u;if(i)return DIGITOR_RESULT_NOT_FOUND;x->plugin_id="transition.paid";x->version="1.0.0";x->package_sha256=SHA;x->install_path="plugins/transition.paid/1.0.0";x->kind=DIGITOR_PLUGIN_APP_TRANSITION;return DIGITOR_RESULT_OK;}
static DigitorResult recover(void* u,const char*i,const char*v,const char*s,char*d,size_t c){(void)i;(void)v;(void)s;if(c)d[0]=0;((State*)u)->recoveries++;return DIGITOR_RESULT_OK;}
static DigitorResult process(void* u,const void*r,char*d,size_t c){if(!r)return DIGITOR_RESULT_INVALID_ARGUMENT;if(c)d[0]=0;((State*)u)->processes++;return DIGITOR_RESULT_OK;}
int main(void){State s={0};DigitorPluginAppHostC h={0};h.struct_size=sizeof(h);h.user_data=&s;h.catalog_count=catalog_count;h.catalog_read=catalog_read;h.compatibility=compatible;h.install=install;h.update=update;h.uninstall=uninstall;h.installed_count=installed_count;h.installed_read=installed_read;h.recover_exact=recover;h.process=process;DigitorPluginAppIntegrationC*p=0;if(digitor_plugin_app_integration_create(&h,&p)!=DIGITOR_RESULT_OK)return 1;size_t n=0;if(digitor_plugin_app_catalog_count(p,&n)!=DIGITOR_RESULT_OK||n!=3)return 2;DigitorPluginAppCatalogItemC item={0};item.struct_size=sizeof(item);if(digitor_plugin_app_catalog_read(p,2,"bn",&item)!=DIGITOR_RESULT_OK||item.kind!=DIGITOR_PLUGIN_APP_TRANSITION)return 3;DigitorPluginAppCompatibilityC status;char d[128];if(digitor_plugin_app_check_compatibility(p,&item,&status,d,sizeof(d))!=DIGITOR_RESULT_OK)return 4;if(digitor_plugin_app_install(p,item.plugin_id,item.version,d,sizeof(d))!=DIGITOR_RESULT_OK)return 5;if(digitor_plugin_app_update(p,item.plugin_id,"1.1.0",d,sizeof(d))!=DIGITOR_RESULT_OK)return 6;if(digitor_plugin_app_recover_exact(p,item.plugin_id,item.version,SHA,d,sizeof(d))!=DIGITOR_RESULT_OK)return 7;if(digitor_plugin_app_process(p,&item,d,sizeof(d))!=DIGITOR_RESULT_OK)return 8;if(digitor_plugin_app_uninstall(p,item.plugin_id,item.version,d,sizeof(d))!=DIGITOR_RESULT_OK)return 9;if(s.installs!=1||s.updates!=1||s.recoveries!=1||s.processes!=1||s.uninstalls!=1)return 10;digitor_plugin_app_integration_destroy(p);puts("PLUGIN_APP_INTEGRATION_QUALIFIED=1");puts("FILTER_EFFECT_TRANSITION_LIFECYCLE=1");puts("COMMERCIAL_POLICY_IN_ENGINE=0");puts("MAIN_RENDERING_FEATURES_CHANGED=0");return 0;}
