# CMake generated Testfile for 
# Source directory: /home/runner/work/DigitorEngine/DigitorEngine
# Build directory: /home/runner/work/DigitorEngine/DigitorEngine/build-pr348
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[digitor_tests]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_tests")
set_tests_properties([=[digitor_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;305;add_test;/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;0;;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;10;include;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_native_gpu_tests]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_native_gpu_tests")
set_tests_properties([=[digitor_native_gpu_tests]=] PROPERTIES  ENVIRONMENT "DIGITOR_GPU_VALIDATION=1" LABELS "native-gpu;hardware" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;316;add_test;/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;0;;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;10;include;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_log_wheels_native_tests]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_log_wheels_native_tests")
set_tests_properties([=[digitor_log_wheels_native_tests]=] PROPERTIES  ENVIRONMENT "DIGITOR_GPU_VALIDATION=1" LABELS "native-gpu;hardware;log-wheels;v4.9.0" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;332;add_test;/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;0;;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;10;include;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_hsl_qualifier_native_tests]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_hsl_qualifier_native_tests")
set_tests_properties([=[digitor_hsl_qualifier_native_tests]=] PROPERTIES  ENVIRONMENT "DIGITOR_GPU_VALIDATION=1" LABELS "native-gpu;hardware;hsl-qualifier;v5.0.0" SKIP_RETURN_CODE "77" _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;348;add_test;/home/runner/work/DigitorEngine/DigitorEngine/cmake/DigitorEngineBase.cmake;0;;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;10;include;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_audio_latency_probe]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_audio_latency_probe_test")
set_tests_properties([=[digitor_audio_latency_probe]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;167;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_audio_sync_compensation]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_audio_sync_compensation_test")
set_tests_properties([=[digitor_audio_sync_compensation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;168;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_professional_audio_engine]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_professional_audio_engine_test")
set_tests_properties([=[digitor_professional_audio_engine]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;169;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_live_playback_sync]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_live_playback_sync_test")
set_tests_properties([=[digitor_live_playback_sync]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;170;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_playback_transport]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_playback_transport_test")
set_tests_properties([=[digitor_playback_transport]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;171;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_playback_engine]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_playback_engine_test")
set_tests_properties([=[digitor_production_playback_engine]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;172;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_unified_real_media_runtime]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_unified_real_media_runtime_test")
set_tests_properties([=[digitor_unified_real_media_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;173;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_media_graph_runtime]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_media_graph_runtime_test")
set_tests_properties([=[digitor_production_media_graph_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;174;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_flutter_production_host_adapter]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_flutter_production_host_adapter_test")
set_tests_properties([=[digitor_flutter_production_host_adapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;175;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_flutter_production_plugin_bootstrap]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_flutter_production_plugin_bootstrap_test")
set_tests_properties([=[digitor_flutter_production_plugin_bootstrap]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;176;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_integration_runtime]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_integration_runtime_test")
set_tests_properties([=[digitor_production_integration_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;177;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_engine_owned_platform_production]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_engine_owned_platform_production_test")
set_tests_properties([=[digitor_engine_owned_platform_production]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;178;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_media_c_api]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_media_c_api_test")
set_tests_properties([=[digitor_production_media_c_api]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;179;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_multitrack_timeline]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_multitrack_timeline_test")
set_tests_properties([=[digitor_multitrack_timeline]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;180;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_professional_timeline_suite]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_professional_timeline_suite_test")
set_tests_properties([=[digitor_professional_timeline_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;181;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_editing_suite]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_editing_suite_test")
set_tests_properties([=[digitor_timeline_editing_suite]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;182;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_completion]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_completion_test")
set_tests_properties([=[digitor_timeline_completion]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;183;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_track_removal]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_track_removal_test")
set_tests_properties([=[digitor_timeline_track_removal]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;184;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_track_enablement]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_track_enablement_test")
set_tests_properties([=[digitor_timeline_track_enablement]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;185;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_export]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_export_test")
set_tests_properties([=[digitor_production_export]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;186;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_ffmpeg_export_runtime]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_ffmpeg_export_runtime_test")
set_tests_properties([=[digitor_ffmpeg_export_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;187;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_hardware_export_runtime]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_hardware_export_runtime_test")
set_tests_properties([=[digitor_hardware_export_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;188;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_hardware_encode]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_hardware_encode_test")
set_tests_properties([=[digitor_production_hardware_encode]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;189;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_export_job_c_api]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_export_job_c_api_test")
set_tests_properties([=[digitor_export_job_c_api]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;190;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_resumable_segment_export]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_resumable_segment_export_test")
set_tests_properties([=[digitor_resumable_segment_export]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;191;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_render_execution]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_render_execution_test")
set_tests_properties([=[digitor_timeline_render_execution]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;192;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_render_runtime]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_render_runtime_test")
set_tests_properties([=[digitor_timeline_render_runtime]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;193;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_timeline_media_adapter]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_timeline_media_adapter_test")
set_tests_properties([=[digitor_timeline_media_adapter]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;194;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_image_io]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_image_io_test")
set_tests_properties([=[digitor_image_io]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;195;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_native_still_image_host]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_native_still_image_host_test")
set_tests_properties([=[digitor_native_still_image_host]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;196;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_native_preview_presentation]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_native_preview_presentation_test")
set_tests_properties([=[digitor_native_preview_presentation]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;197;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_production_hardware_decode]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_production_hardware_decode_test")
set_tests_properties([=[digitor_production_hardware_decode]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;198;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_native_surface_import]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_native_surface_import_test")
set_tests_properties([=[digitor_native_surface_import]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;199;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_professional_import]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_professional_import_test")
set_tests_properties([=[digitor_professional_import]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;200;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_professional_color_management]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_professional_color_management_test")
set_tests_properties([=[digitor_professional_color_management]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;201;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_ocio_color_pipeline]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_ocio_color_pipeline_test")
set_tests_properties([=[digitor_ocio_color_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;202;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_icc_display_management]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_icc_display_management_test")
set_tests_properties([=[digitor_icc_display_management]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;203;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_camera_raw]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_camera_raw_test")
set_tests_properties([=[digitor_camera_raw]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;204;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_hdr_ecosystem]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_hdr_ecosystem_test")
set_tests_properties([=[digitor_hdr_ecosystem]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;205;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_professional_lut_scopes]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_professional_lut_scopes_test")
set_tests_properties([=[digitor_professional_lut_scopes]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;206;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
add_test([=[digitor_broadcast_color_matching]=] "/home/runner/work/DigitorEngine/DigitorEngine/build-pr348/digitor_broadcast_color_matching_test")
set_tests_properties([=[digitor_broadcast_color_matching]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;207;add_test;/home/runner/work/DigitorEngine/DigitorEngine/CMakeLists.txt;0;")
