#include "digitor/digitor.h"
#include "digitor/renderer.hpp"
#include <algorithm>
#include <cmath>
#include <mutex>
#include <thread>

struct DigitorSdkSession {
 std::mutex mutex; std::thread worker; std::atomic_bool busy{},cancel{}; int64_t position{}; DigitorColorControls color{0,1,1}; std::vector<uint8_t> texture; uint32_t width{},height{}; uint64_t generation{};
 digitor::SharedRenderer renderer;
 DigitorSdkSession():renderer([this](auto&g,const auto&r,auto&out){auto target=g.create_transient(uint64_t(r.width)*r.height*16);g.add_pass({"flutter-preview",{},{{target,digitor::ResourceState::shader_write}},[&,this](auto&e){e.dispatch([&,this]{out.pixels.resize(size_t(r.width)*r.height);DigitorColorControls c;{std::scoped_lock lock(mutex);c=color;}for(uint32_t y=0;y<r.height;++y)for(uint32_t x=0;x<r.width;++x){float red=r.width>1?float(x)/float(r.width-1):0,green=r.height>1?float(y)/float(r.height-1):0;auto grade=[&](float v){v=(v-.5f)*c.contrast+.5f+c.exposure*.1f;float l=(red+green+.5f)/3;return std::clamp(l+(v-l)*c.saturation,0.f,1.f);};out.pixels[size_t(y)*r.width+x]={grade(red),grade(green),grade(.5f),1};}});}});}){}
};
namespace { bool valid(DigitorSdkSession*s){return s!=nullptr;} void join_old(DigitorSdkSession*s){if(s->worker.joinable())s->worker.join();} }
DigitorResult digitor_sdk_create(DigitorSdkSession**out){if(!out)return DIGITOR_RESULT_INVALID_ARGUMENT;try{*out=new DigitorSdkSession;return DIGITOR_RESULT_OK;}catch(...){return DIGITOR_RESULT_OUT_OF_MEMORY;}}
DigitorResult digitor_sdk_destroy(DigitorSdkSession*s){if(!valid(s))return DIGITOR_RESULT_INVALID_ARGUMENT;s->cancel=true;join_old(s);delete s;return DIGITOR_RESULT_OK;}
DigitorResult digitor_sdk_set_color(DigitorSdkSession*s,DigitorColorControls c){if(!valid(s)||!std::isfinite(c.exposure)||!std::isfinite(c.contrast)||!std::isfinite(c.saturation))return DIGITOR_RESULT_INVALID_ARGUMENT;std::scoped_lock lock(s->mutex);s->color=c;return DIGITOR_RESULT_OK;}
DigitorResult digitor_sdk_preview_async(DigitorSdkSession*s,int64_t frame,uint32_t w,uint32_t h,DigitorAsyncCallback cb,void*u){if(!valid(s)||!w||!h||frame<0)return DIGITOR_RESULT_INVALID_ARGUMENT;if(s->busy.exchange(true))return DIGITOR_RESULT_RESOURCE_IN_USE;join_old(s);s->cancel=false;s->worker=std::thread([=]{DigitorResult result=DIGITOR_RESULT_OK;try{auto f=s->renderer.render({frame,w,h,{}});if(!s->cancel){std::vector<uint8_t>pixels(f.pixels.size()*4);for(size_t i=0;i<f.pixels.size();++i){auto cv=[](float v){return uint8_t(std::clamp(v,0.f,1.f)*255+.5f);};pixels[i*4]=cv(f.pixels[i].r);pixels[i*4+1]=cv(f.pixels[i].g);pixels[i*4+2]=cv(f.pixels[i].b);pixels[i*4+3]=cv(f.pixels[i].a);}std::scoped_lock lock(s->mutex);s->texture=std::move(pixels);s->width=w;s->height=h;s->position=frame;++s->generation;}}catch(...){result=DIGITOR_RESULT_INTERNAL_ERROR;}s->busy=false;if(cb)cb(result,u);});return DIGITOR_RESULT_OK;}
DigitorResult digitor_sdk_seek_async(DigitorSdkSession*s,int64_t frame,DigitorAsyncCallback cb,void*u){if(!valid(s)||frame<0)return DIGITOR_RESULT_INVALID_ARGUMENT;if(s->busy.exchange(true))return DIGITOR_RESULT_RESOURCE_IN_USE;join_old(s);s->worker=std::thread([=]{s->position=frame;s->busy=false;if(cb)cb(DIGITOR_RESULT_OK,u);});return DIGITOR_RESULT_OK;}
DigitorResult digitor_sdk_get_native_texture(DigitorSdkSession*s,DigitorNativeTexture*out){if(!valid(s)||!out)return DIGITOR_RESULT_INVALID_ARGUMENT;std::scoped_lock lock(s->mutex);out->pixels=s->texture.data();out->width=s->width;out->height=s->height;out->row_bytes=s->width*4;out->generation=s->generation;return s->texture.empty()?DIGITOR_RESULT_NOT_INITIALIZED:DIGITOR_RESULT_OK;}
DigitorResult digitor_sdk_export_async(DigitorSdkSession*s,const char*path,int32_t format,int32_t codec,int64_t first,int64_t last,uint32_t w,uint32_t h,DigitorExportProgressCallback progress,DigitorAsyncCallback done,void*u){if(!valid(s)||!path||first<0||last<first||!w||!h||format<0||format>5||codec<0||codec>2)return DIGITOR_RESULT_INVALID_ARGUMENT;if(s->busy.exchange(true))return DIGITOR_RESULT_RESOURCE_IN_USE;join_old(s);s->cancel=false;std::string output(path);s->worker=std::thread([=]{DigitorResult result=DIGITOR_RESULT_OK;try{digitor::ExportSettings settings;settings.format=static_cast<digitor::ExportFormat>(format);settings.video_codec=static_cast<digitor::VideoCodec>(codec);settings.first=first;settings.last=last;settings.width=w;settings.height=h;settings.cancel=std::shared_ptr<std::atomic_bool>(&s->cancel,[](auto*){});settings.progress=[=](const digitor::ExportProgress&p){if(progress)progress(p.fraction,p.completed,p.total,u);};digitor::ExportRenderer(s->renderer).export_to(output,settings);}catch(...){result=DIGITOR_RESULT_INTERNAL_ERROR;}s->busy=false;if(done)done(result,u);});return DIGITOR_RESULT_OK;}
DigitorResult digitor_sdk_cancel(DigitorSdkSession*s){if(!valid(s))return DIGITOR_RESULT_INVALID_ARGUMENT;s->cancel=true;return DIGITOR_RESULT_OK;}
