function(digitor_configure_android_gles_effect_provider target)
  if(NOT ANDROID)
    message(FATAL_ERROR "Android GLES effect provider may only be configured for Android")
  endif()
  if(NOT TARGET ${target})
    message(FATAL_ERROR "Android GLES effect provider target does not exist: ${target}")
  endif()
  get_filename_component(_digitor_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  target_sources(${target} PRIVATE
    "${_digitor_root}/src/platform/android/android_gles_effect_provider.cpp")
  target_include_directories(${target} PRIVATE "${_digitor_root}/include")
  target_link_libraries(${target} PRIVATE EGL GLESv3)
  target_compile_definitions(${target} PRIVATE DIGITOR_ANDROID_GLES_EFFECTS=1)
endfunction()
