if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
  message(FATAL_ERROR "embed_spirv.cmake requires INPUT, OUTPUT and SYMBOL")
endif()
file(READ "${INPUT}" HEXDATA HEX)
string(LENGTH "${HEXDATA}" HEX_LENGTH)
math(EXPR BYTE_COUNT "${HEX_LENGTH} / 2")
set(VALUES "")
set(INDEX 0)
while(INDEX LESS HEX_LENGTH)
  string(SUBSTRING "${HEXDATA}" ${INDEX} 8 WORD_HEX)
  string(LENGTH "${WORD_HEX}" WORD_LENGTH)
  if(NOT WORD_LENGTH EQUAL 8)
    message(FATAL_ERROR "SPIR-V byte count must be a multiple of four: ${INPUT}")
  endif()
  string(SUBSTRING "${WORD_HEX}" 0 2 B0)
  string(SUBSTRING "${WORD_HEX}" 2 2 B1)
  string(SUBSTRING "${WORD_HEX}" 4 2 B2)
  string(SUBSTRING "${WORD_HEX}" 6 2 B3)
  string(APPEND VALUES "0x${B3}${B2}${B1}${B0}u,")
  math(EXPR INDEX "${INDEX} + 8")
endwhile()
file(WRITE "${OUTPUT}" "#pragma once\n#include <cstddef>\n#include <cstdint>\ninline constexpr std::uint32_t ${SYMBOL}[] = {${VALUES}};\ninline constexpr std::size_t ${SYMBOL}_word_count = sizeof(${SYMBOL}) / sizeof(${SYMBOL}[0]);\n")
