#include "digitor/color_pipeline.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace digitor { namespace {
struct Hsv{float h,s,v;};Hsv hsv(Color c){float hi=std::max({c.r,c.g,c.b}),lo=std::min({c.r,c.g,c.b}),d=hi-lo,h=0;if(d){if(hi==c.r)h=std::fmod((c.g-c.b)/d,6.f);else if(hi==c.g)h=(c.b-c.r)/d+2;else h=(c.r-c.g)/d+4;h/=6;if(h<0)h++;}return{h,hi?d/hi:0,hi};}Color rgb(Hsv x,float a){x.h-=std::floor(x.h);float q=x.h*6,i=std::floor(q),f=q-i,p=x.v*(1-x.s),u=x.v*(1-x.s*f),t=x.v*(1-x.s*(1-f));switch((int)i%6){case 0:return{x.v,t,p,a};case 1:return{u,x.v,p,a};case 2:return{p,x.v,t,a};case 3:return{p,u,x.v,a};case 4:return{t,p,x.v,a};default:return{x.v,p,u,a};}}
Color run(Color c,const ColorPipelineParameters&p){c=grade_color(c,p.primary);c={p.red.sample(c.r),p.green.sample(c.g),p.blue.sample(c.b),c.a};c={p.master.sample(c.r),p.master.sample(c.g),p.master.sample(c.b),c.a};auto h=hsv(c);float lum=.2126f*c.r+.7152f*c.g+.0722f*c.b;h.h+=p.hue_vs_hue.sample(h.h)-h.h;h.s*=std::max(0.f,p.hue_vs_sat.sample(h.h)*p.sat_vs_sat.sample(h.s)*p.lum_vs_sat.sample(lum));c=rgb(h,c.a);float hl=p.hue_vs_lum.sample(h.h);c.r*=hl;c.g*=hl;c.b*=hl;auto wheel=[&](float v,float lift,float gamma,float gain){return std::copysign(std::pow(std::abs((v+lift)*gain),1/std::max(.001f,gamma)),v+lift);};c.r=wheel(c.r,p.lift_wheel.r,p.gamma_wheel.r+1,p.gain_wheel.r+1);c.g=wheel(c.g,p.lift_wheel.g,p.gamma_wheel.g+1,p.gain_wheel.g+1);c.b=wheel(c.b,p.lift_wheel.b,p.gamma_wheel.b+1,p.gain_wheel.b+1);return c;}
}
Curve::Curve():points_{{0,0},{1,1}}{}Curve::Curve(std::vector<CurvePoint>p):points_(std::move(p)){if(points_.size()<2)throw std::invalid_argument("curve needs two points");std::sort(points_.begin(),points_.end(),[](auto a,auto b){return a.x<b.x;});for(size_t i=1;i<points_.size();i++)if(points_[i].x==points_[i-1].x)throw std::invalid_argument("duplicate curve point");}float Curve::sample(float x)const{if(x<=points_.front().x)return points_.front().y;if(x>=points_.back().x)return points_.back().y;auto b=std::upper_bound(points_.begin(),points_.end(),x,[](float v,auto p){return v<p.x;});auto a=b-1;float t=(x-a->x)/(b->x-a->x);return a->y+(b->y-a->y)*t;}
ColorShaderGraph::ColorShaderGraph():schedule_{ColorPass::primary,ColorPass::curves,ColorPass::hue_curves,ColorPass::wheels}{}void ColorShaderGraph::process_cpu(std::span<const Color>i,std::span<Color>o,const ColorPipelineParameters&p)const{if(i.size()!=o.size())throw std::invalid_argument("image sizes differ");for(size_t n=0;n<i.size();n++)o[n]=run(i[n],p);}void ColorShaderGraph::process_gpu(CommandEncoder&e,std::span<const Color>i,std::span<Color>o,const ColorPipelineParameters&p){auto&s=shaders_.get_or_compile(compiler_,ShaderLanguage::glsl,ShaderStage::compute,"layout(local_size_x=64) in; void main(){}");pipelines_.get_or_create({s.hash});e.dispatch([=,this]{process_cpu(i,o,p);});}
}
