#include "digitor/color_pipeline.hpp"
#include "core/engine.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace digitor { namespace {
struct Hsv{float h,s,v;};Hsv hsv(Color c){float hi=std::max({c.r,c.g,c.b}),lo=std::min({c.r,c.g,c.b}),d=hi-lo,h=0;if(d!=0.0f){if(hi==c.r)h=std::fmod((c.g-c.b)/d,6.f);else if(hi==c.g)h=(c.b-c.r)/d+2;else h=(c.r-c.g)/d+4;h/=6;if(h<0)h++;}return{h,hi!=0.0f?d/hi:0.0f,hi};}Color rgb(Hsv x,float a){x.h-=std::floor(x.h);float q=x.h*6,i=std::floor(q),f=q-i,p=x.v*(1-x.s),u=x.v*(1-x.s*f),t=x.v*(1-x.s*(1-f));switch(static_cast<int>(i)%6){case 0:return{x.v,t,p,a};case 1:return{u,x.v,p,a};case 2:return{p,x.v,t,a};case 3:return{p,u,x.v,a};case 4:return{t,p,x.v,a};default:return{x.v,p,u,a};}}
Color run(Color c,const ColorPipelineParameters&p){c=grade_color(c,p.primary);c={p.red.sample(c.r),p.green.sample(c.g),p.blue.sample(c.b),c.a};c={p.master.sample(c.r),p.master.sample(c.g),p.master.sample(c.b),c.a};auto h=hsv(c);float lum=.2126f*c.r+.7152f*c.g+.0722f*c.b;h.h+=p.hue_vs_hue.sample(h.h)-h.h;h.s*=std::max(0.f,p.hue_vs_sat.sample(h.h)*p.sat_vs_sat.sample(h.s)*p.lum_vs_sat.sample(lum));c=rgb(h,c.a);float hl=p.hue_vs_lum.sample(h.h);c.r*=hl;c.g*=hl;c.b*=hl;auto wheel=[&](float v,float lift,float gamma,float gain){return std::copysign(std::pow(std::abs((v+lift)*gain),1/std::max(.001f,gamma)),v+lift);};c.r=wheel(c.r,p.lift_wheel.r,p.gamma_wheel.r+1,p.gain_wheel.r+1);c.g=wheel(c.g,p.lift_wheel.g,p.gamma_wheel.g+1,p.gain_wheel.g+1);c.b=wheel(c.b,p.lift_wheel.b,p.gamma_wheel.b+1,p.gain_wheel.b+1);return c;}
}
Curve::Curve():points_{{0,0},{1,1}}{}Curve::Curve(std::vector<CurvePoint>p):points_(std::move(p)){if(points_.size()<2)throw std::invalid_argument("curve needs two points");std::sort(points_.begin(),points_.end(),[](auto a,auto b){return a.x<b.x;});for(size_t i=1;i<points_.size();i++)if(points_[i].x==points_[i-1].x)throw std::invalid_argument("duplicate curve point");}float Curve::sample(float x)const{if(x<=points_.front().x)return points_.front().y;if(x>=points_.back().x)return points_.back().y;auto b=std::upper_bound(points_.begin(),points_.end(),x,[](float v,auto p){return v<p.x;});auto a=b-1;float t=(x-a->x)/(b->x-a->x);return a->y+(b->y-a->y)*t;}
bool identity(const Curve&c){auto&p=c.points();return p.size()==2&&p[0].x==0&&p[0].y==0&&p[1].x==1&&p[1].y==1;}
bool future_parameters(const ColorPipelineParameters&p){return !identity(p.red)||!identity(p.green)||!identity(p.blue)||!identity(p.master)||!identity(p.hue_vs_hue)||!identity(p.hue_vs_sat)||!identity(p.hue_vs_lum)||!identity(p.sat_vs_sat)||!identity(p.lum_vs_sat)||p.lift_wheel.r||p.lift_wheel.g||p.lift_wheel.b||p.gamma_wheel.r||p.gamma_wheel.g||p.gamma_wheel.b||p.gain_wheel.r||p.gain_wheel.g||p.gain_wheel.b;}
ColorShaderGraph::ColorShaderGraph():schedule_{ColorPass::temperature,ColorPass::tint,ColorPass::saturation,ColorPass::contrast,ColorPass::lift,ColorPass::gain,ColorPass::offset,ColorPass::exposure,ColorPass::gamma,ColorPass::hue}{}
void ColorShaderGraph::process_cpu(std::span<const Color>i,std::span<Color>o,const ColorPipelineParameters&p)const{if(i.size()!=o.size())throw std::invalid_argument("image sizes differ");for(size_t n=0;n<i.size();n++)o[n]=run(i[n],p);}
void ColorShaderGraph::process_gpu(CommandEncoder&e,std::span<const Color>i,std::span<Color>o,const ColorPipelineParameters&p){if(i.size()!=o.size())throw std::invalid_argument("image sizes differ");if(future_parameters(p))throw std::invalid_argument("curves and wheels are not native GPU stages in v4.6");grade_image_gpu(e,i.data(),o.data(),i.size(),p.primary);}
std::size_t ColorShaderGraph::shader_cache_size()const{return shaders_.size();}std::size_t ColorShaderGraph::pipeline_cache_size()const{return pipelines_.size();}
ColorValidationMetrics validate_color_pipeline(std::span<const Color>a,std::span<const Color>b,ShaderBackend backend,float at,float rt){if(a.size()!=b.size()||at<0||rt<0)throw std::invalid_argument("invalid color validation input");ColorValidationMetrics m;m.backend=backend;double squares=0,signal=0,mean_a=0,mean_b=0;std::size_t samples=a.size()*4,fail=static_cast<size_t>(-1);for(size_t n=0;n<a.size();++n)for(size_t k=0;k<4;++k){float x=(&a[n].r)[k],y=(&b[n].r)[k],ae=std::abs(x-y),re=ae/std::max(std::abs(x),1e-20f);if(ae>m.maximum_absolute_error){m.maximum_absolute_error=ae;m.worst_pixel=n;}m.maximum_relative_error=std::max(m.maximum_relative_error,re);squares+=double(ae)*ae;signal=std::max(signal,double(std::abs(x)));mean_a+=x;mean_b+=y;if(fail==static_cast<size_t>(-1)&&ae>at&&re>rt)fail=n;}m.first_failing_pixel=fail;m.rms=samples?float(std::sqrt(squares/samples)):0;m.psnr=m.rms==0?INFINITY:float(20*std::log10((signal?signal:1)/m.rms));if(!samples){m.ssim=1;}else{mean_a/=samples;mean_b/=samples;double va=0,vb=0,cov=0;for(size_t n=0;n<a.size();++n)for(size_t k=0;k<4;++k){double x=(&a[n].r)[k]-mean_a,y=(&b[n].r)[k]-mean_b;va+=x*x;vb+=y*y;cov+=x*y;}va/=samples;vb/=samples;cov/=samples;constexpr double c1=1e-4,c2=9e-4;m.ssim=float(((2*mean_a*mean_b+c1)*(2*cov+c2))/((mean_a*mean_a+mean_b*mean_b+c1)*(va+vb+c2)));}m.passed=fail==static_cast<size_t>(-1);return m;}
}
