#ifdef __ANDROID__
#include <GLES3/gl3.h>
#include <cstring>
#include "gpu/gpu_backend.hpp"
namespace digitor { namespace { struct GlObject{GLuint name;}; class GlBackend final:public IRenderBackend{DigitorRendererInfo i_{};public:GlBackend(){i_.backend=DIGITOR_RENDERER_OPENGL_ES;strcpy(i_.backend_name,"OpenGL ES");strcpy(i_.device_name,"Current EGL context");i_.is_gpu=i_.supports_fp32=1;}bool initialize(bool)override{return glGetString(GL_VERSION)!=nullptr;}void shutdown()noexcept override{}DigitorRendererInfo info()const noexcept override{return i_;}DigitorResult create_texture(const DigitorTextureDesc&d,void**o)noexcept override{*o=nullptr;GLenum in=0,format=GL_RGBA,type=GL_UNSIGNED_BYTE;switch(d.format){case DIGITOR_PIXEL_FORMAT_RGBA8_UNORM:in=GL_RGBA8;break;case DIGITOR_PIXEL_FORMAT_RGBA16_FLOAT:in=GL_RGBA16F;type=GL_HALF_FLOAT;break;case DIGITOR_PIXEL_FORMAT_RGBA32_FLOAT:in=GL_RGBA32F;type=GL_FLOAT;break;default:return DIGITOR_RESULT_UNSUPPORTED;}auto*p=new(std::nothrow)GlObject{};if(!p)return DIGITOR_RESULT_OUT_OF_MEMORY;glGenTextures(1,&p->name);glBindTexture(GL_TEXTURE_2D,p->name);glTexImage2D(GL_TEXTURE_2D,0,in,d.width,d.height,0,format,type,nullptr);if(glGetError()!=GL_NO_ERROR){glDeleteTextures(1,&p->name);delete p;return DIGITOR_RESULT_BACKEND_UNAVAILABLE;}*o=p;return DIGITOR_RESULT_OK;}DigitorResult create_buffer(const DigitorBufferDesc&d,void**o)noexcept override{auto*p=new(std::nothrow)GlObject{};if(!p)return DIGITOR_RESULT_OUT_OF_MEMORY;glGenBuffers(1,&p->name);glBindBuffer(GL_ARRAY_BUFFER,p->name);glBufferData(GL_ARRAY_BUFFER,(GLsizeiptr)d.size,nullptr,(d.usage&DIGITOR_BUFFER_USAGE_UPLOAD)?GL_STREAM_DRAW:GL_STATIC_DRAW);if(glGetError()!=GL_NO_ERROR){glDeleteBuffers(1,&p->name);delete p;return DIGITOR_RESULT_OUT_OF_MEMORY;}*o=p;return DIGITOR_RESULT_OK;}DigitorResult create_sampler(const DigitorSamplerDesc&,void**o)noexcept override{auto*p=new(std::nothrow)GlObject{};if(!p)return DIGITOR_RESULT_OUT_OF_MEMORY;glGenSamplers(1,&p->name);*o=p;return glGetError()==GL_NO_ERROR?DIGITOR_RESULT_OK:DIGITOR_RESULT_BACKEND_UNAVAILABLE;}void destroy_texture(void*p)noexcept override{auto*x=(GlObject*)p;if(x){glDeleteTextures(1,&x->name);delete x;}}void destroy_buffer(void*p)noexcept override{auto*x=(GlObject*)p;if(x){glDeleteBuffers(1,&x->name);delete x;}}void destroy_sampler(void*p)noexcept override{auto*x=(GlObject*)p;if(x){glDeleteSamplers(1,&x->name);delete x;}}};}std::unique_ptr<IRenderBackend>create_native_backend(DigitorRendererBackend b){
#ifdef DIGITOR_HAS_VULKAN
extern std::unique_ptr<IRenderBackend> create_vulkan_backend(); if(b==DIGITOR_RENDERER_VULKAN)return create_vulkan_backend();
#endif
return b==DIGITOR_RENDERER_OPENGL_ES?std::make_unique<GlBackend>():nullptr;}}
#endif
