#import <Metal/Metal.h>
#include <cstring>
#include "gpu/gpu_backend.hpp"
namespace digitor { namespace {
class MetalBackend final:public IRenderBackend { id<MTLDevice> device_; DigitorRendererInfo info_{};
 static MTLPixelFormat fmt(DigitorPixelFormat f){switch(f){case DIGITOR_PIXEL_FORMAT_RGBA8_UNORM:return MTLPixelFormatRGBA8Unorm;case DIGITOR_PIXEL_FORMAT_BGRA8_UNORM:return MTLPixelFormatBGRA8Unorm;case DIGITOR_PIXEL_FORMAT_RGBA16_FLOAT:return MTLPixelFormatRGBA16Float;case DIGITOR_PIXEL_FORMAT_RGBA32_FLOAT:return MTLPixelFormatRGBA32Float;default:return MTLPixelFormatInvalid;}}
public: MetalBackend(id<MTLDevice>d):device_(d){info_.backend=DIGITOR_RENDERER_METAL;strcpy(info_.backend_name,"Metal");strncpy(info_.device_name,d.name.UTF8String,127);info_.is_gpu=info_.supports_compute=info_.supports_fp16=info_.supports_fp32=1;}bool initialize(bool)override{return true;}void shutdown()noexcept override{}DigitorRendererInfo info()const noexcept override{return info_;}
DigitorResult create_texture(const DigitorTextureDesc&d,void**o)noexcept override{@autoreleasepool{*o=nullptr;auto*x=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:fmt(d.format) width:d.width height:d.height mipmapped:NO];x.storageMode=MTLStorageModePrivate;x.usage=0;if(d.usage&DIGITOR_TEXTURE_USAGE_SAMPLED)x.usage|=MTLTextureUsageShaderRead;if(d.usage&DIGITOR_TEXTURE_USAGE_STORAGE)x.usage|=MTLTextureUsageShaderWrite;if(d.usage&DIGITOR_TEXTURE_USAGE_RENDER_TARGET)x.usage|=MTLTextureUsageRenderTarget;id<MTLTexture>v=[device_ newTextureWithDescriptor:x];if(!v)return DIGITOR_RESULT_OUT_OF_MEMORY;*o=(__bridge_retained void*)v;return DIGITOR_RESULT_OK;}}
DigitorResult create_buffer(const DigitorBufferDesc&d,void**o)noexcept override{@autoreleasepool{*o=nullptr;MTLResourceOptions opts=(d.usage&(DIGITOR_BUFFER_USAGE_UPLOAD|DIGITOR_BUFFER_USAGE_STAGING))?MTLResourceStorageModeShared:MTLResourceStorageModePrivate;id<MTLBuffer>v=[device_ newBufferWithLength:(NSUInteger)d.size options:opts];if(!v)return DIGITOR_RESULT_OUT_OF_MEMORY;*o=(__bridge_retained void*)v;return DIGITOR_RESULT_OK;}}
DigitorResult create_sampler(const DigitorSamplerDesc&d,void**o)noexcept override{@autoreleasepool{MTLSamplerDescriptor*x=[MTLSamplerDescriptor new];x.minFilter=d.min_filter?MTLSamplerMinMagFilterLinear:MTLSamplerMinMagFilterNearest;x.magFilter=d.mag_filter?MTLSamplerMinMagFilterLinear:MTLSamplerMinMagFilterNearest;x.normalizedCoordinates=d.normalized_coordinates;id<MTLSamplerState>v=[device_ newSamplerStateWithDescriptor:x];if(!v)return DIGITOR_RESULT_OUT_OF_MEMORY;*o=(__bridge_retained void*)v;return DIGITOR_RESULT_OK;}}
DigitorResult map_buffer(void*p,uint64_t offset,uint64_t,void**o)noexcept override{if(!p||!o)return DIGITOR_RESULT_INVALID_ARGUMENT;id<MTLBuffer>b=(__bridge id<MTLBuffer>)p;void*base=[b contents];if(!base){*o=nullptr;return DIGITOR_RESULT_UNSUPPORTED;}*o=(uint8_t*)base+offset;return DIGITOR_RESULT_OK;}void unmap_buffer(void*)noexcept override{}
DigitorResult render_rgba8(uint32_t w,uint32_t h,std::span<const uint8_t> source,std::vector<uint8_t>& out)noexcept override{@autoreleasepool{
 if(!w||!h||(!source.empty()&&source.size()!=size_t(w)*h*4))return DIGITOR_RESULT_INVALID_ARGUMENT;
 MTLTextureDescriptor*td=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm width:w height:h mipmapped:NO];td.usage=MTLTextureUsageRenderTarget|MTLTextureUsageShaderRead;td.storageMode=MTLStorageModeShared;id<MTLTexture> target=[device_ newTextureWithDescriptor:td];id<MTLCommandQueue>queue=[device_ newCommandQueue];if(!target||!queue)return DIGITOR_RESULT_BACKEND_UNAVAILABLE;
 id<MTLCommandBuffer>cb=[queue commandBuffer];if(source.empty()){MTLRenderPassDescriptor*rp=[MTLRenderPassDescriptor renderPassDescriptor];rp.colorAttachments[0].texture=target;rp.colorAttachments[0].loadAction=MTLLoadActionClear;rp.colorAttachments[0].storeAction=MTLStoreActionStore;rp.colorAttachments[0].clearColor=MTLClearColorMake(0,0,0,1);[[cb renderCommandEncoderWithDescriptor:rp] endEncoding];}else{[target replaceRegion:MTLRegionMake2D(0,0,w,h) mipmapLevel:0 withBytes:source.data() bytesPerRow:w*4];}
 [cb commit];[cb waitUntilCompleted];if(cb.status!=MTLCommandBufferStatusCompleted)return DIGITOR_RESULT_BACKEND_UNAVAILABLE;try{out.resize(size_t(w)*h*4);}catch(...){return DIGITOR_RESULT_OUT_OF_MEMORY;}[target getBytes:out.data() bytesPerRow:w*4 fromRegion:MTLRegionMake2D(0,0,w,h) mipmapLevel:0];return DIGITOR_RESULT_OK;}}
void destroy_texture(void*p)noexcept override{if(p)CFRelease(p);}void destroy_buffer(void*p)noexcept override{if(p)CFRelease(p);}void destroy_sampler(void*p)noexcept override{if(p)CFRelease(p);}};}
std::unique_ptr<IRenderBackend> create_native_backend(DigitorRendererBackend b){if(b!=DIGITOR_RENDERER_METAL)return nullptr;id<MTLDevice>d=MTLCreateSystemDefaultDevice();return d?std::make_unique<MetalBackend>(d):nullptr;}}
