#import <Metal/Metal.h>
#include <cstring>
#include "gpu/gpu_backend.hpp"
namespace digitor { namespace {
class MetalBackend final:public IRenderBackend { id<MTLDevice> device_; DigitorRendererInfo info_{};
 static MTLPixelFormat fmt(DigitorPixelFormat f){switch(f){case DIGITOR_PIXEL_FORMAT_RGBA8_UNORM:return MTLPixelFormatRGBA8Unorm;case DIGITOR_PIXEL_FORMAT_BGRA8_UNORM:return MTLPixelFormatBGRA8Unorm;case DIGITOR_PIXEL_FORMAT_RGBA16_FLOAT:return MTLPixelFormatRGBA16Float;case DIGITOR_PIXEL_FORMAT_RGBA32_FLOAT:return MTLPixelFormatRGBA32Float;default:return MTLPixelFormatInvalid;}}
public: MetalBackend(id<MTLDevice>d):device_(d){info_.backend=DIGITOR_RENDERER_METAL;strcpy(info_.backend_name,"Metal");strncpy(info_.device_name,d.name.UTF8String,127);info_.is_gpu=info_.supports_compute=info_.supports_fp16=info_.supports_fp32=1;}bool initialize(bool)override{return true;}void shutdown()noexcept override{}DigitorRendererInfo info()const noexcept override{return info_;}
DigitorResult create_texture(const DigitorTextureDesc&d,void**o)noexcept override{@autoreleasepool{*o=nullptr;auto*x=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:fmt(d.format) width:d.width height:d.height mipmapped:NO];x.storageMode=MTLStorageModePrivate;x.usage=0;if(d.usage&DIGITOR_TEXTURE_USAGE_SAMPLED)x.usage|=MTLTextureUsageShaderRead;if(d.usage&DIGITOR_TEXTURE_USAGE_STORAGE)x.usage|=MTLTextureUsageShaderWrite;if(d.usage&DIGITOR_TEXTURE_USAGE_RENDER_TARGET)x.usage|=MTLTextureUsageRenderTarget;id<MTLTexture>v=[device_ newTextureWithDescriptor:x];if(!v)return DIGITOR_RESULT_OUT_OF_MEMORY;*o=(__bridge_retained void*)v;return DIGITOR_RESULT_OK;}}
DigitorResult create_buffer(const DigitorBufferDesc&d,void**o)noexcept override{@autoreleasepool{*o=nullptr;MTLResourceOptions opts=(d.usage&(DIGITOR_BUFFER_USAGE_UPLOAD|DIGITOR_BUFFER_USAGE_STAGING))?MTLResourceStorageModeShared:MTLResourceStorageModePrivate;id<MTLBuffer>v=[device_ newBufferWithLength:(NSUInteger)d.size options:opts];if(!v)return DIGITOR_RESULT_OUT_OF_MEMORY;*o=(__bridge_retained void*)v;return DIGITOR_RESULT_OK;}}
DigitorResult create_sampler(const DigitorSamplerDesc&d,void**o)noexcept override{@autoreleasepool{MTLSamplerDescriptor*x=[MTLSamplerDescriptor new];x.minFilter=d.min_filter?MTLSamplerMinMagFilterLinear:MTLSamplerMinMagFilterNearest;x.magFilter=d.mag_filter?MTLSamplerMinMagFilterLinear:MTLSamplerMinMagFilterNearest;x.normalizedCoordinates=d.normalized_coordinates;id<MTLSamplerState>v=[device_ newSamplerStateWithDescriptor:x];if(!v)return DIGITOR_RESULT_OUT_OF_MEMORY;*o=(__bridge_retained void*)v;return DIGITOR_RESULT_OK;}}
void destroy_texture(void*p)noexcept override{if(p)CFRelease(p);}void destroy_buffer(void*p)noexcept override{if(p)CFRelease(p);}void destroy_sampler(void*p)noexcept override{if(p)CFRelease(p);}};}
std::unique_ptr<IRenderBackend> create_native_backend(DigitorRendererBackend b){if(b!=DIGITOR_RENDERER_METAL)return nullptr;id<MTLDevice>d=MTLCreateSystemDefaultDevice();return d?std::make_unique<MetalBackend>(d):nullptr;}}
