#include "digitor/native_node_executor.hpp"
#include "gpu/gpu_backend.hpp"
#include <exception>
#include <unordered_map>
namespace digitor {
namespace { struct NativeValue{ProcessedGpuFramePtr frame;bool source{};}; bool mask(NodeOperationKind k){return k==NodeOperationKind::hsl_qualifier||k==NodeOperationKind::power_window;} }
NativeNodeGraphPreflight preflight_native_node_graph(const IRenderBackend& backend,const ProductionNodeGraph& graph) noexcept{
 NativeNodeGraphPreflight out{true,0,NodeOperationKind::primary_wheels,{}};try{for(auto id:graph.execution_order()){const auto&n=graph.node(id);if(n.kind==ProductionNodeKind::mixer&&!backend.supports_native_node_mixer()){out.supported=false;out.node=id;out.message="backend does not implement native parallel mixer";return out;}for(const auto&op:n.operations){if(!op.enabled)continue;if(mask(op.kind)){out.supported=false;out.node=id;out.operation=op.kind;out.message="backend lacks node-local matte plus masked-composite semantics";return out;}if(!backend.supports_native_node_operation(op.kind)){out.supported=false;out.node=id;out.operation=op.kind;out.message="backend does not implement selected-node native operation";return out;}}}}catch(const std::exception&e){out.supported=false;out.message=e.what();}catch(...){out.supported=false;out.message="unknown native graph preflight error";}return out;
}
NativeNodeGraphResult execute_native_node_graph(IRenderBackend&backend,const ProductionNodeGraph&graph,std::span<const Color>source,std::uint32_t width,std::uint32_t height,std::int64_t timestamp) noexcept{
 NativeNodeGraphResult r{};auto pf=preflight_native_node_graph(backend,graph);if(!pf.supported){r.status=pf.message.find("mixer")!=std::string::npos?NativeNodeGraphStatus::unsupported_parallel_mixer:NativeNodeGraphStatus::unsupported_operation;r.node=pf.node;r.operation=pf.operation;r.backend_result=DIGITOR_RESULT_UNSUPPORTED;r.message=pf.message;return r;}try{if(!width||!height||source.size()!=std::size_t(width)*height){r.message="invalid source frame";return r;}std::unordered_map<NodeId,NativeValue>out;out[graph.input_node()]={{},true};ProcessedGpuFramePtr last;
 for(auto id:graph.execution_order()){const auto&n=graph.node(id);if(n.kind==ProductionNodeKind::input)continue;if(n.kind==ProductionNodeKind::output){if(n.inputs.size()!=1||!out.contains(n.inputs.front())){r.node=id;r.message="output node has no native input";return r;}auto v=out.at(n.inputs.front());if(!v.frame){r.status=NativeNodeGraphStatus::unsupported_operation;r.backend_result=DIGITOR_RESULT_UNSUPPORTED;r.node=id;r.message="identity-only graph requires backend-native source upload/pass-through";return r;}last=v.frame;break;}
  if(n.kind==ProductionNodeKind::mixer){std::vector<GpuSourceResource>sources;bool all_source=!n.inputs.empty();for(auto input:n.inputs){if(!out.contains(input)){r.node=id;r.message="mixer input is unavailable";return r;}auto v=out.at(input);all_source&=v.source;if(v.frame)sources.push_back(backend.gpu_source(v.frame));}if(all_source){out[id]={{},true};continue;}if(sources.size()!=n.inputs.size()){r.status=NativeNodeGraphStatus::unsupported_parallel_mixer;r.backend_result=DIGITOR_RESULT_UNSUPPORTED;r.node=id;r.message="parallel mixer requires source upload for an unprocessed branch";return r;}ProcessedGpuFramePtr mixed;auto dr=backend.mix_gpu_sources(sources,timestamp,mixed);if(dr!=DIGITOR_RESULT_OK||!mixed){r.status=NativeNodeGraphStatus::backend_failure;r.backend_result=dr;r.node=id;r.message="backend-native parallel mixer failed";return r;}out[id]={std::move(mixed),false};continue;}
  if(n.inputs.size()!=1||!out.contains(n.inputs.front())){r.node=id;r.message="grade node must have exactly one available input";return r;}NativeValue current=out.at(n.inputs.front());if(!n.enabled||n.bypassed||n.operations.empty()){out[id]=current;continue;}for(const auto&op:n.operations){if(!op.enabled)continue;ProcessedGpuFramePtr next;DigitorResult dr=DIGITOR_RESULT_BACKEND_UNAVAILABLE;bool first=!current.frame&&current.source;switch(op.kind){case NodeOperationKind::primary_wheels:{auto p=std::get<std::shared_ptr<const PrimaryWheelsParameters>>(op.payload);dr=first?backend.process_primary_wheels_gpu(source,width,height,timestamp,*p,next):backend.process_primary_wheels_gpu(backend.gpu_source(current.frame),timestamp,*p,next);break;}case NodeOperationKind::log_wheels:{auto p=std::get<std::shared_ptr<const LogWheelsParameters>>(op.payload);dr=first?backend.process_log_wheels_gpu(source,width,height,timestamp,*p,next):backend.process_log_wheels_gpu(backend.gpu_source(current.frame),timestamp,*p,next);break;}case NodeOperationKind::rgb_curves:{auto p=std::get<std::shared_ptr<const CompiledRgbCurves>>(op.payload);dr=first?backend.process_curves_gpu(source,width,height,timestamp,*p,next):backend.process_curves_gpu(backend.gpu_source(current.frame),timestamp,*p,next);break;}case NodeOperationKind::hsl_qualifier:case NodeOperationKind::power_window:r.status=NativeNodeGraphStatus::unsupported_operation;r.backend_result=DIGITOR_RESULT_UNSUPPORTED;r.node=id;r.operation=op.kind;r.message="mask operation reached executor without semantic preflight";return r;default:if(first){r.status=NativeNodeGraphStatus::unsupported_operation;r.backend_result=DIGITOR_RESULT_UNSUPPORTED;r.node=id;r.operation=op.kind;r.message="first native node operation requires source-upload capable pass";return r;}dr=backend.process_node_operation_gpu(backend.gpu_source(current.frame),timestamp,op,next);break;}if(dr!=DIGITOR_RESULT_OK||!next){r.status=dr==DIGITOR_RESULT_UNSUPPORTED?NativeNodeGraphStatus::unsupported_operation:NativeNodeGraphStatus::backend_failure;r.backend_result=dr;r.node=id;r.operation=op.kind;r.message=dr==DIGITOR_RESULT_UNSUPPORTED?"backend does not implement selected-node native pass":"backend-native node pass failed";return r;}current={std::move(next),false};}out[id]=std::move(current);
 }
 if(!last){r.status=NativeNodeGraphStatus::unsupported_operation;r.backend_result=DIGITOR_RESULT_UNSUPPORTED;r.message="graph produced no final native GPU frame";return r;}r.status=NativeNodeGraphStatus::ok;r.backend_result=DIGITOR_RESULT_OK;r.frame=std::move(last);r.message="native GPU-only DAG execution completed";return r;}catch(const std::exception&e){r.message=e.what();return r;}catch(...){r.message="unknown native graph error";return r;}
}
}