#include "digitor/production_motion_blur.hpp"
#include <algorithm>
#include <cmath>
namespace digitor { namespace {
float clamp01(float v){ return std::clamp(v,0.0f,1.0f); }
bool valid(const MotionBlurSettings& s){ return s.shutter_angle>=0.0f&&s.shutter_angle<=360.0f&&s.samples>=1u&&s.samples<=64u&&s.motion_scale>=0.0f&&s.motion_scale<=8.0f&&s.confidence_floor>=0.0f&&s.confidence_floor<=1.0f; }
MotionBlurPixel sample(const MotionBlurFrame& f,float x,float y){ x=std::clamp(x,0.0f,float(f.width-1)); y=std::clamp(y,0.0f,float(f.height-1)); auto x0=std::uint32_t(x),y0=std::uint32_t(y),x1=std::min(x0+1,f.width-1),y1=std::min(y0+1,f.height-1); float tx=x-x0,ty=y-y0; auto lerp=[](float a,float b,float t){return a+(b-a)*t;}; auto p00=f.pixels[std::size_t(y0)*f.width+x0],p10=f.pixels[std::size_t(y0)*f.width+x1],p01=f.pixels[std::size_t(y1)*f.width+x0],p11=f.pixels[std::size_t(y1)*f.width+x1]; MotionBlurPixel o; o.r=lerp(lerp(p00.r,p10.r,tx),lerp(p01.r,p11.r,tx),ty); o.g=lerp(lerp(p00.g,p10.g,tx),lerp(p01.g,p11.g,tx),ty); o.b=lerp(lerp(p00.b,p10.b,tx),lerp(p01.b,p11.b,tx),ty); o.a=lerp(lerp(p00.a,p10.a,tx),lerp(p01.a,p11.a,tx),ty); return o; }
std::uint64_t append(std::uint64_t h,const void* p,std::size_t n){ auto b=static_cast<const unsigned char*>(p); for(std::size_t i=0;i<n;++i){h^=b[i];h*=1099511628211ull;} return h; }
}
std::uint64_t motion_blur_frame_digest(const MotionBlurFrame& f) noexcept { std::uint64_t h=1469598103934665603ull; h=append(h,&f.width,sizeof f.width); h=append(h,&f.height,sizeof f.height); if(!f.pixels.empty()) h=append(h,f.pixels.data(),f.pixels.size()*sizeof(MotionBlurPixel)); return h; }
MotionBlurResult apply_motion_blur_reference(const MotionBlurFrame& in,const std::vector<MotionVector>& mv,MotionBlurFrame& out,const MotionBlurSettings& s){ MotionBlurResult r; if(!valid(s)||in.width==0||in.height==0||in.pixels.size()!=std::size_t(in.width)*in.height||mv.size()!=in.pixels.size()) return r; out.width=in.width;out.height=in.height;out.pixels.resize(in.pixels.size()); float shutter=s.shutter_angle/360.0f; for(std::uint32_t y=0;y<in.height;++y) for(std::uint32_t x=0;x<in.width;++x){ auto i=std::size_t(y)*in.width+x; auto m=mv[i]; float c=clamp01((m.confidence-s.confidence_floor)/std::max(0.0001f,1.0f-s.confidence_floor)); float dx=m.x*s.motion_scale*shutter*c,dy=m.y*s.motion_scale*shutter*c; MotionBlurPixel sum{}; for(std::uint32_t k=0;k<s.samples;++k){ float t=s.samples==1?0.0f:float(k)/float(s.samples-1); if(s.center_exposure)t-=0.5f; auto p=sample(in,float(x)+dx*t,float(y)+dy*t); sum.r+=p.r;sum.g+=p.g;sum.b+=p.b;sum.a+=p.a;} float inv=1.0f/float(s.samples); sum.r=clamp01(sum.r*inv);sum.g=clamp01(sum.g*inv);sum.b=clamp01(sum.b*inv);sum.a=clamp01(sum.a*inv); out.pixels[i]=sum;} r.status=MotionBlurStatus::ready;r.digest=motion_blur_frame_digest(out);return r; }
MotionBlurResult dispatch_motion_blur_gpu(const MotionBlurDispatchPacket& p,const MotionBlurDispatch& d){ MotionBlurResult r; if(p.backend==MotionBlurBackend::cpu||p.width==0||p.height==0||p.input_handle==0||p.motion_handle==0||p.output_handle==0||p.command_handle==0||!valid(p.settings)) return r; if(!d){r.status=MotionBlurStatus::backend_unavailable;return r;} r.status=d(p)?MotionBlurStatus::ready:MotionBlurStatus::dispatch_failed;return r; }
}
