#include "digitor/production_lens_distortion.hpp"
#include <algorithm>
#include <cmath>

namespace digitor { namespace {
float clamp01(float v){return std::clamp(v,0.0f,1.0f);} 
float mirror(float v){v=std::fmod(std::fabs(v),2.0f);return v>1.0f?2.0f-v:v;}
bool valid(const LensDistortionSettings&s){return std::isfinite(s.k1)&&std::isfinite(s.k2)&&std::isfinite(s.k3)&&std::isfinite(s.p1)&&std::isfinite(s.p2)&&s.scale>0&&s.aspect>0&&s.center_x>=0&&s.center_x<=1&&s.center_y>=0&&s.center_y<=1&&s.chromatic_aberration>=0&&s.chromatic_aberration<=0.1f;}
std::uint64_t append(std::uint64_t h,const void*p,std::size_t n){const auto*b=static_cast<const unsigned char*>(p);for(std::size_t i=0;i<n;++i){h^=b[i];h*=1099511628211ull;}return h;}
LensPixel sample(const LensFrame&f,float u,float v,LensEdgeMode e){if(e==LensEdgeMode::mirror){u=mirror(u);v=mirror(v);}else if(e==LensEdgeMode::clamp){u=clamp01(u);v=clamp01(v);}else if(u<0||u>1||v<0||v>1)return{};float x=u*(f.width-1),y=v*(f.height-1);auto x0=static_cast<std::uint32_t>(x),y0=static_cast<std::uint32_t>(y);auto x1=std::min(x0+1,f.width-1),y1=std::min(y0+1,f.height-1);float tx=x-x0,ty=y-y0;auto p00=f.pixels[std::size_t(y0)*f.width+x0],p10=f.pixels[std::size_t(y0)*f.width+x1],p01=f.pixels[std::size_t(y1)*f.width+x0],p11=f.pixels[std::size_t(y1)*f.width+x1];LensPixel o;float*w=&o.r;const float*a=&p00.r,*b=&p10.r,*c=&p01.r,*d=&p11.r;for(int i=0;i<4;++i)w[i]=((a[i]*(1-tx)+b[i]*tx)*(1-ty)+(c[i]*(1-tx)+d[i]*tx)*ty);return o;}
void map(float u,float v,const LensDistortionSettings&s,float&su,float&sv){float x=(u-s.center_x)*2.0f*s.aspect/s.scale,y=(v-s.center_y)*2.0f/s.scale;float r2=x*x+y*y,radial=1+s.k1*r2+s.k2*r2*r2+s.k3*r2*r2*r2;float dx=2*s.p1*x*y+s.p2*(r2+2*x*x),dy=s.p1*(r2+2*y*y)+2*s.p2*x*y;if(s.mode==LensMode::correct){for(int i=0;i<5;++i){float rr=x*x+y*y,rd=1+s.k1*rr+s.k2*rr*rr+s.k3*rr*rr*rr;x=(x-dx)/rd;y=(y-dy)/rd;}}else{x=x*radial+dx;y=y*radial+dy;}su=s.center_x+x*s.scale/(2*s.aspect);sv=s.center_y+y*s.scale/2;}
}}
std::uint64_t lens_frame_digest(const LensFrame&f) noexcept{std::uint64_t h=1469598103934665603ull;h=append(h,&f.width,sizeof f.width);h=append(h,&f.height,sizeof f.height);if(!f.pixels.empty())h=append(h,f.pixels.data(),f.pixels.size()*sizeof(LensPixel));return h;}
LensResult apply_lens_distortion_reference(const LensFrame&in,LensFrame&out,const LensDistortionSettings&s){LensResult r;if(!valid(s)||!in.width||!in.height||in.pixels.size()!=std::size_t(in.width)*in.height)return r;out={in.width,in.height,{}};out.pixels.resize(in.pixels.size());for(std::uint32_t y=0;y<in.height;++y)for(std::uint32_t x=0;x<in.width;++x){float u=float(x)/std::max(1u,in.width-1),v=float(y)/std::max(1u,in.height-1),su,sv;map(u,v,s,su,sv);if(s.chromatic_aberration>0){auto pr=sample(in,su+s.chromatic_aberration,sv,s.edge_mode),pg=sample(in,su,sv,s.edge_mode),pb=sample(in,su-s.chromatic_aberration,sv,s.edge_mode);out.pixels[std::size_t(y)*in.width+x]={pr.r,pg.g,pb.b,pg.a};}else out.pixels[std::size_t(y)*in.width+x]=sample(in,su,sv,s.edge_mode);}r.status=LensStatus::ready;r.digest=lens_frame_digest(out);return r;}
LensResult dispatch_lens_distortion_gpu(const LensDispatchPacket&p,const LensDispatch&d){LensResult r;if(p.backend==LensBackend::cpu||!p.width||!p.height||!p.input_handle||!p.output_handle||!p.command_handle||!valid(p.settings))return r;if(!d){r.status=LensStatus::backend_unavailable;return r;}r.status=d(p)?LensStatus::ready:LensStatus::dispatch_failed;return r;}
}
extern "C" std::uint32_t digitor_lens_distortion_rgba32f(const float*in,float*out,std::uint32_t w,std::uint32_t h,const DigitorLensDistortionSettings*c,std::uint64_t*d){if(!in||!out||!c||!d||!w||!h)return 1;digitor::LensFrame f{w,h,{}};f.pixels.resize(std::size_t(w)*h);for(std::size_t i=0;i<f.pixels.size();++i)f.pixels[i]={in[i*4],in[i*4+1],in[i*4+2],in[i*4+3]};digitor::LensDistortionSettings s;s.mode=static_cast<digitor::LensMode>(c->mode);s.edge_mode=static_cast<digitor::LensEdgeMode>(c->edge_mode);s.k1=c->k1;s.k2=c->k2;s.k3=c->k3;s.p1=c->p1;s.p2=c->p2;s.center_x=c->center_x;s.center_y=c->center_y;s.scale=c->scale;s.aspect=c->aspect;s.chromatic_aberration=c->chromatic_aberration;s.high_quality=c->high_quality!=0;digitor::LensFrame o;auto r=digitor::apply_lens_distortion_reference(f,o,s);if(r.status!=digitor::LensStatus::ready)return 2;for(std::size_t i=0;i<o.pixels.size();++i){out[i*4]=o.pixels[i].r;out[i*4+1]=o.pixels[i].g;out[i*4+2]=o.pixels[i].b;out[i*4+3]=o.pixels[i].a;}*d=r.digest;return 0;}
